### PR TITLE
chore: remove automation to pull gherkin specs

### PR DESCRIPTION
**Pull request by mdelapenya**
## What does this PR do?
This PR removes the existing automation to pull the gherkin specs from the APM repository, as following updates will come in the way of a PR to this repo.

## Checklist

~~- [ ] My code follows the [style guidelines of this project](CONTRIBUTING.md#java-language-formatting-guidelines)~~
- [x] I have rebased my changes on top of the latest master branch

~~- [ ] I have made corresponding changes to the documentation~~
~~- [ ] I have added tests that prove my fix is effective or that my feature works~~
~~- [ ] New and existing [**unit** tests](https://github.com/elastic/apm-agent-java/blob/master/CONTRIBUTING.md#testing) pass locally with my changes~~

~~- [ ] I have updated [CHANGELOG.asciidoc](CHANGELOG.asciidoc)~~
~~- [ ] I have updated [supported-technologies.asciidoc](docs/supported-technologies.asciidoc)~~
~~- [ ] Added an API method or config option? Document in which version this will be introduced~~
~~- [ ] Added an instrumentation plugin? How did you make sure that old, non-supported versions are not instrumented by accident?~~

## Related issues

- Relates https://github.com/elastic/apm/pull/231

<!-- _(Optional)_
Add here screenshots about how the project will be changed after the PR is applied. They could be related to web pages, terminal, etc, or any other image you consider important to be shared with the team.

### CODE REVIEW

**Comment by mdelapenya** [comment]
BTW, I found this flakiness in a CI build: is it happening at any other build?
https://apm-ci.elastic.co/job/apm-agent-java/job/apm-agent-java-mbp/job/PR-1105/1/testReport/

**Comment by felixbarny** [comment]
Thanks for reporting the flaky tests. I've created an issue template, a `flaky-tests` tag and two issues to start the fight against the flakiness ✊ 

It would be great to have statistics over what the flakiest tests are so we can fight the overall flakiness more effectively.

**Comment by SylvainJuge** [comment]
I'm not really sure about completely removing those scripts, for example we sometimes have to work on specs that are in-progress and thus not yet merged on master.

In that case, does it mean that we have to use a manual copy of the files from apm repository in order to be able to work on a different version ? Or is there a way to trigger the "automatically create PR job" to run on another branch of apm and open PR with a different target branch ?

That's probably not a big deal, and we can use a manual copy, but given agents tend to have different implementation timelines that might happen quite often in practice.

**Comment by felixbarny** [comment]
I think it's fine having to manually copy a spec if it's still a (draft) PR. The norm should be that only approved spec changes are used by the agents.

Personally, by the time I look up which parameters I have to set in order to specify the PR branch, I can just copy/paste from the PR 😅

**Comment by cachedout** [comment]
@felixbarny Regarding flaky tests, we have some ideas about how to produce reports that we'll be working on and will be available to all Observability teams. In the meantime, I wonder if you might be interested in exploring using the capability of Maven Surefire to re-run tests X number of times if they fail. Here is a commit message in the maven surefire repo describing this capability:

https://github.com/apache/maven-surefire/commit/fefaae7f0534a59f52c046a64c96987e8561dd48

**Comment by cachedout** [comment]
> I haven't found a really decent alternative that works with Junit5, also if we have a common way to track flaky tests, we could also apply it to other agent builds and integration tests.

OK, sounds good. We'll keep you updated on our progress with flaky test reporting.

**Pull request merged**
