### PR TITLE
Support for setting the application class loader for a transaction via the public api

### PR DESCRIPTION
**Pull request by tobiasstadler**
## What does this PR do?
Implements the solution suggested in #2369

## Checklist
- [x] This is an enhancement of existing features, or a new feature in existing plugins
  - [x] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/main/CHANGELOG.asciidoc)
  - [x] I have added tests that prove my fix is effective or that my feature works
  - [x] Added an API method or config option? Document in which version this will be introduced
  - [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by felixbarny — APPROVED** [review]
I've added some changes, let me know if this works for you.
LGTM, but I'd like to wait for @eyalkoren's feedback before merging

**Comment by felixbarny** [comment]
run elasticsearch-ci/docs

**Review by felixbarny — APPROVED** [review]

**Comment by felixbarny** [comment]
run elasticsearch-ci/docs

**Comment by tobiasstadler** [comment]
> I've added some changes, let me know if this works for you.

Much better that what I did! Thank you for your support.

Yes, service name/version and MDC work for me.

**Comment by felixbarny** [comment]
run elasticsearch-ci/docs

**Comment by eyalkoren** [comment]
I actually intend to get rid of `TraceContext#applicationClassLoader` as part of #2428 ...
We don't need this reference anymore and it's always a good idea to store one less weak reference (and any CL reference).
Since you are actually only interested in the implicit side-effect of `TraceContext#setApplicationClassLoader`, which is to override the service info for the transaction, the API seems inappropriate to me. Calling it `overrideServiceInfoFor(ClassLoader)` would be better (the javadoc would how the provided `ClassLoader` is used).

Generally speaking, I would prefer a cleaner and more generic API such as `overrideServiceInfo(String serviceName, String serviceVersion)`. If extracting the service version and name are simple enough- just implement that instead of relying on the automatic discovery. If relying on the automatic discovery is important, I assume this is mostly relevant for external plugins (not for other usages of the API), so we can expose `ElasticApmTracer#getServiceInfo(ClassLoader)` through the sdk by making it part of the `co.elastic.apm.agent.impl.Tracer` interface. WDYT?

**Comment by tobiasstadler** [comment]
Hm, I find it quite inconvenient to (always) have to to call `getServiceInfo` before I can call `overrideServiceInfo`. What about something like `Transaction#withServiceInfoForClassCloader(ClassLoader)` (or maybe use instead of with or another better name) or #2369. What do you think.

@eyalkoren I will implement your suggestion in the next days

**Comment by tobiasstadler** [comment]
@eyalkoren Please see #2451 for my implementation of your suggestion

**Comment by tobiasstadler** [comment]
#2451 is the preferred api

**Pull request closed without merging**
