### PR TITLE
Try to fix flaky VertxServerTest

### PR DESCRIPTION
**Pull request by tobiasstadler**
## What does this PR do?
Try to fix VertxServerTest by letting VertX choose a random port

## Checklist
- [x] This is something else
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)

### CODE REVIEW

**Comment by tobiasstadler** [comment]
@eyalkoren Would you mind running the tests again?

**Comment by eyalkoren** [comment]
@tobiasstadler it looks good, I believe this failure is related to #2354 

@Mergifyio update

**Comment by tobiasstadler** [comment]
@eyalkoren Would you please run the /test and run elasticsearch-ci/docs

**Comment by eyalkoren** [comment]
run elasticsearch-ci/docs

**Comment by tobiasstadler** [comment]
Thank You!

**Comment by tobiasstadler** [comment]
```
Error processing tar file(exit status 1): write /var/cache/debconf/templates.dat-old: no space left on device
	at co.elastic.apm.servlet.PayaraIT.<init>(PayaraIT.java:37)
```
:cry:

**Comment by eyalkoren** [comment]
@Mergifyio update

/test

**Comment by tobiasstadler** [comment]
It finally passed the tests. Would you please merge it?

**Review by jackshirazi — APPROVED** [review]
Thank you!

**Comment by tobiasstadler** [comment]
Thank You!

**Pull request merged**
