### PR TITLE
Restore "known old version of byte-buddy" in runtime-attach-app

### PR DESCRIPTION
**Pull request by tobiasstadler**
## What does this PR do?
Restored "known old version of byte-buddy" (see #2116)

## Checklist
- [x] This is something else
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)

### CODE REVIEW

**Comment by tobiasstadler** [comment]
@SylvainJuge Since you introduced the "known old version of byte-buddy", would you please have look?

**Comment by SylvainJuge** [comment]
What is really weird here is that this byte buddy artifact should have been ignored thanks to the changes introduced in https://github.com/elastic/apm-agent-java/pull/2252.

**Review by SylvainJuge — APPROVED** [review]

**Comment by tobiasstadler** [comment]
The version was (manually) changed in #2251

**Comment by tobiasstadler** [comment]
run elasticsearch-ci/docs

**Comment by eyalkoren** [comment]
run elasticsearch-ci/docs

**Comment by tobiasstadler** [comment]
Thank You!

**Pull request merged**
