### PR TITLE
Set transaction type only if unset

### PR DESCRIPTION
**Pull request by kelunik**
## What does this PR do?

This PR avoids overwriting a custom transaction type if set by the application.

Currently, changing the transaction type in an application has no effect, because it is changed by `ServletTransactionHelper` again.

Separating transaction types is necessary if you want to separate main requests from internal RPC requests for example.

## Checklist

- [x] This is an enhancement of existing features, or a new feature in existing plugins
  - [x] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/main/CHANGELOG.asciidoc)
  - [x] I have added tests that prove my fix is effective or that my feature works
  - [ ] ~~Added an API method or config option? Document in which version this will be introduced~~
  - [ ] ~~I have made corresponding changes to the documentation~~
- [ ] This is a bugfix
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/main/CHANGELOG.asciidoc)
  - [ ] I have added tests that would fail without this fix
- [ ] This is a new plugin
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/main/CHANGELOG.asciidoc)
  - [ ] My code follows the [style guidelines of this project](https://github.com/elastic/apm-agent-java/blob/main/CONTRIBUTING.md#java-language-formatting-guidelines)
  - [ ] I have made corresponding changes to the documentation
  - [ ] I have added tests that prove my fix is effective or that my feature works
  - [ ] New and existing [**unit** tests](https://github.com/elastic/apm-agent-java/blob/main/CONTRIBUTING.md#testing) pass locally with my changes
  - [ ] I have updated [supported-technologies.asciidoc](https://github.com/elastic/apm-agent-java/blob/main/docs/supported-technologies.asciidoc)
  - [ ] Added an API method or config option? Document in which version this will be introduced
  - [ ] Added an instrumentation plugin? Describe how you made sure that old, non-supported versions are not instrumented by accident.
- [ ] This is something else
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/main/CHANGELOG.asciidoc)

### CODE REVIEW

**Review by JonasKunz — COMMENTED** [review]
Thanks for your contribution!
It indeed does make sense to allow overriding the transaction type.
I've added a testcase proving your fix works as desired and added a changelog for you.

Could you please sign the CLA so that we can merge this PR?

**Comment by kelunik** [comment]
Hey @JonasKunz,

Thanks for the review and test! I have the CLA on my list, unfortunately it needs to go through legal before I can submit it.

**Comment by JonasKunz** [comment]
run elasticsearch-ci/docs

**Comment by JonasKunz** [comment]
run elasticsearch-ci/docs

**Comment by kelunik** [comment]
@JonasKunz Thank you for the tests and handling with the CLA!

**Pull request merged**
