### PR TITLE
Fix Nullpointer risk

### PR DESCRIPTION
**Pull request by Edimz**
I'm getting a Nullpointer here since my implementation does not contain the field "connected". Maybe reflection can't find it in my superclass.

## What does this PR do?
I added a declaring type of "connected" to prevent nullpointer exception when not using the field in a subclass.

## Checklist

- [x] This is an enhancement of existing features, or a new feature in existing plugins
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)
  - [ ] I have added tests that prove my fix is effective or that my feature works
  - [ ] Added an API method or config option? Document in which version this will be introduced
  - [ ] I have made corresponding changes to the documentation
- [ ] This is a bugfix
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)
  - [ ] I have added tests that would fail without this fix
- [ ] This is a new plugin
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)
  - [ ] My code follows the [style guidelines of this project](https://github.com/elastic/apm-agent-java/blob/master/CONTRIBUTING.md#java-language-formatting-guidelines)
  - [ ] I have made corresponding changes to the documentation
  - [ ] I have added tests that prove my fix is effective or that my feature works
  - [ ] New and existing [**unit** tests](https://github.com/elastic/apm-agent-java/blob/master/CONTRIBUTING.md#testing) pass locally with my changes
  - [ ] I have updated [supported-technologies.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/docs/supported-technologies.asciidoc)
  - [ ] Added an API method or config option? Document in which version this will be introduced
  - [ ] Added an instrumentation plugin? Describe how you made sure that old, non-supported versions are not instrumented by accident.
- [ ] This is something else
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)

### CODE REVIEW

**Comment by eyalkoren** [comment]
Thanks for reporting and suggesting a fix!
The `connected` variable is primitive, so I can't see how this fix prevents this NPE. I assume the error is thrown when Byte Buddy fails to assign a value for it because it can't find it in the class.
Please provide the entire NPE message and stack trace.

> my implementation does not contain "connected"

Can you elaborate - what is "your" implementation? Is it some custom implementation of `java.net.HttpURLConnection`? Can you share this code?

**Comment by SylvainJuge** [comment]
Hi @Edimz which version of the JDK was used when you had `NullPointerException` triggered without this change ?
While providing a unit test to reproduce/validate that change might be tricky, being able to reproduce it once locally with the exact same JDK version might be enough here.

**Comment by Edimz** [comment]
@eyalkoren, you are correct, my quick fix was not good, I changed to

```
@Advice.FieldValue(value = "connected",
                                       declaringType = URLConnection.class) boolean connected

```
And that made the trick, tho I got a new Nullpointer that I do not know how to fix, yet.

**Comment by Edimz** [comment]
@SylvainJuge I just tested with another fix (correct one) but still get Nullpointer on another parameter (thiz.getURL() is null), I think I'll disable inferred spans until I've debugged this thoroughly.

**Comment by eyalkoren** [comment]
@Edimz we will be glad if you can answer our questions:
- What JDK did are you using when seeing this error?
- What is the exact class that extends `java.net.HttpURLConnection` that is related to the error?
- Can you provide a stack trace of this error?

Please either answer those so that we can follow up, or close this issue if it is irrelevant anymore.
Thanks!

**Comment by eyalkoren** [comment]
Closing as we got no feedback. If required, we can always reopen.

**Pull request closed without merging**
