### PR TITLE
fix premature recycling

### PR DESCRIPTION
**Pull request by jackshirazi**
## What does this PR do?
Moves the parent.decrementReferences() call from Span.beforeEnd() to Span.afterEnd()

## Checklist
- [ ] This is an enhancement of existing features, or a new feature in existing plugins
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/main/CHANGELOG.asciidoc)
  - [ ] I have added tests that prove my fix is effective or that my feature works
  - [ ] Added an API method or config option? Document in which version this will be introduced
  - [ ] I have made corresponding changes to the documentation
- [x] This is a bugfix
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/main/CHANGELOG.asciidoc)
  - [ ] I have added tests that would fail without this fix
- [ ] This is a new plugin
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/main/CHANGELOG.asciidoc)
  - [ ] My code follows the [style guidelines of this project](https://github.com/elastic/apm-agent-java/blob/main/CONTRIBUTING.md#java-language-formatting-guidelines)
  - [ ] I have made corresponding changes to the documentation
  - [ ] I have added tests that prove my fix is effective or that my feature works
  - [ ] New and existing [**unit** tests](https://github.com/elastic/apm-agent-java/blob/main/CONTRIBUTING.md#testing) pass locally with my changes
  - [ ] I have updated [supported-technologies.asciidoc](https://github.com/elastic/apm-agent-java/blob/main/docs/supported-technologies.asciidoc)
  - [ ] Added an API method or config option? Document in which version this will be introduced
  - [ ] Added an instrumentation plugin? Describe how you made sure that old, non-supported versions are not instrumented by accident.
- [ ] This is something else
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/main/CHANGELOG.asciidoc)

### CODE REVIEW

**Comment by felixbarny** [comment]
> Moves the parent.decrementReferences() call from Span.beforeEnd() to Span.afterEnd()

I'm not sure if that's enough. As long as the parent is holding a buffered span, it's not safe to decrement references of the parent. Maybe there are more problematic cases but the most problematic one is when the parent is already ended but child spans are created and compressed. In this case, the compressed spans will never get reported. That's because a compressed span is reported when its parent ends (see [spec](https://github.com/elastic/apm/blame/main/specs/agents/handling-huge-traces/tracing-spans-compress.md#L164)). Therefore, we'll probably have to adjust the spec so that a span is only [eligible for compression](https://github.com/elastic/apm/blob/main/specs/agents/handling-huge-traces/tracing-spans-compress.md#eligibility-for-compression) if its parent has not ended yet. However, the issue is that this condition may be racy. The parent and child may end concurrently in different threads.

**Comment by jackshirazi** [comment]
I'm rethinking it all. Here's where I am at the moment
1. If there is a concurrent child, decrementReferences() is fine because the parent won't get recycled
2. If there is no concurrent child but there is a buffer, decrementReferences() is fine because the parent won't get recycled, there is still a reference
3. If there is no concurrent child and no buffer, we want to decrementReferences() EXCEPT if this child in the end() call becomes the buffer

The race case where the parent and child are concurrently ended needs the parent to check if it has a buffer and recycle that before recycling itself. You still have the condition where the parent has recycled the buffer before the buffer is ended, still trying to get that one

I'm wondering if the recycling is worth it

**Review by felixbarny — APPROVED** [review]
While there are open questions for the interactions with recycling and span compressions, I feel like this is an incremental improvement that's worth merging in.

**Comment by jackshirazi** [comment]
@felixbarny what do you think about letting the recycle only happen if the bufferedSpan is null? The decrement reference happens after the bufferedSpan is cleared under normal operation, so that would address the edge race case though with the risk that the Span ultimately wouldn't get recycled?

**Comment by jackshirazi** [comment]
This set of changes doesn't fix the issue, but all the changes are needed since the object shouldn't be recycled before the buffer is accessed - which is happening prior to this. I'll look in to reproducing the problem and applying a fix using a different branch. Meanwhile applying this set of changes and including it in the patch

**Pull request merged**
