### PR TITLE
Upgrading Byte Buddy version to 1.12.6

### PR DESCRIPTION
**Pull request by eyalkoren**

### CODE REVIEW

**Comment by v1v** [comment]
Thanks Eyal, I understand now the whole problem! Then I guess the <= should be the way to go as you said

**Review by v1v — APPROVED** [review]

**Comment by tobiasstadler** [comment]
Maybe the problem is that ignore does not check against the version in the pom but the version in "Maven Central"? So an update from < 1.9.16 to version 1.9.16 would be ignored, but not an update from 1.9.16 to something > 1.9.16?

**Comment by tobiasstadler** [comment]
@eyalkoren yes, I also read that. But for me it is not really clear what the ignored version refers to. https://github.community/t/configure-dependabot-to-only-create-prs-for-minor-or-patch-updates/117656 suggests it is the new version not the version in the pom.

**Comment by tobiasstadler** [comment]
Maybe 
```
 - package-ecosystem: "maven"
    directory: "/"
   ....
-  package-ecosystem: "maven"
    directory: "/integration-tests/runtime-attach/runtime-attach-app/"
    ...
    ignore:
      - dependency-name: "net.bytebuddy:byte-buddy-agent"
```
does work?

**Pull request merged**
