### PR TITLE
Use the resource auto-inference to set context.destination.service.resource for JDBC spans (#1913)

### LINKED ISSUE #1913: resource auto-inference is not working for JDBC spans
## Describe the bug
According to https://github.com/elastic/apm/pull/465 `context.destination.service.resource` should be `${subtype}/${instance}` (or `${type}/${instance}` if subtype is null) for a JDBC Span, e.g. for a postgresql db named test: `postgresql/test`. However, `context.destination.service.resource` is only `${subtype}` (or `${type}`), resp. `postgresql ` in the example above.

The algorithm in `co.elastic.apm.agent.impl.transaction.Span#beforeEnd` is not working because:
* JDBC spans are created as normal spans, not exit spans (see `co.elastic.apm.agent.jdbc.helper.JdbcHelper#createJdbcSpan`)
* JDBC spans usually set `context.destination.service.resource` to `ConnectionMetaData.getDbVendor()` (see `co.elastic.apm.agent.jdbc.helper.JdbcHelper#createJdbcSpan`)

## Expected behavior
For a Postgres db named test `context.destination.service.resource` should be `postgresql/test`

### PR DESCRIPTION
**Pull request by tobiasstadler**
## What does this PR do?
Fixes #1913

## Checklist
- [x] This is an enhancement of existing features, or a new feature in existing plugins
  - [x] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)
  - [x] I have added tests that prove my fix is effective or that my feature works
  - [x] Added an API method or config option? Document in which version this will be introduced
  - [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by eyalkoren** [comment]
Yes, I understood what you requested, but this is what I referred to as a patch.
A real config will probably not be such, but more something like: `use_instance_for_db_resource`, and it is relevant to all agents, not only Java. We wouldn't want to let make our users think about auto-inference and how it works, but on what this config would change.

So, let us consider that. Maybe we decide to add this as an `internal` config.

**Comment by tobiasstadler** [comment]
Ok, so should I change my implementation and just add the instance to `context.destination.service.resource` in `JdbcHelper` if the internal config option `use_instance_for_db_resource` is true?

**Comment by tobiasstadler** [comment]
@eyalkoren I implemented your suggestion

**Comment by eyalkoren** [comment]
@tobiasstadler sorry for the long pauses between responses, we are extremely busy these days and I was OOO lately. Let me try pushing https://github.com/elastic/apm/issues/473 forward first, and if we can't get that, we will consider a Java-specific configuration. Normally we try to avoid that, as it make future decisions more complicated.

**Comment by tobiasstadler** [comment]
Ok, thanks you @eyalkoren

**Comment by felixbarny** [comment]
@SylvainJuge is working on a concept that plans to use `service.target.name` and `service.target.type` from [ECS](https://www.elastic.co/guide/en/ecs/master/ecs-service.html#_field_reuse_22) instead.

**Comment by tobiasstadler** [comment]
@SylvainJuge / @felixbarny Is there any (rough) timeline (you can share) when your concept will be available?

**Comment by SylvainJuge** [comment]
Hi @tobiasstadler, we aim to start working on this in the next couple of months. As usual any estimate should be taken with a ~~pinch~~ shovel of salt.

Given it involves changing things in multiple projects: all agents, apm-server and apm-ui it's really hard to give you any estimate when it will be available in practice. However, it's something that is an important on a product level, so it is really something that is expected to happen in the short/mid-term time-frame.

**Comment by tobiasstadler** [comment]
Ok, thank You for the information. I guess I have to wait then.

**Pull request closed without merging**
