### PR TITLE
API Docs | Typo fix for headerExtractor description in Public API

### LINKED ISSUE #1041: Typo in headerExtractor description
## Describe the bug

Typo for the headerExtractor description in:
- https://www.elastic.co/guide/en/apm/agent/java/current/public-api.html#api-start-transaction-with-remote-parent-header
- https://www.elastic.co/guide/en/apm/agent/java/current/public-api.html#api-start-transaction-with-remote-parent-headers

## Steps to reproduce

1. Open above page
2. `headerExtractor` description mentions `returns the fist header with that name`
## Expected behavior

The description should be `returns the first header with that name`

### PR DESCRIPTION
**Pull request by RajatArora08**
## What does this PR do?

Fixes a typo for the `headerExtractor` description in:
- https://www.elastic.co/guide/en/apm/agent/java/current/public-api.html#api-start-transaction-with-remote-parent-header
- https://www.elastic.co/guide/en/apm/agent/java/current/public-api.html#api-start-transaction-with-remote-parent-headers

## Checklist

- [X] My code follows the [style guidelines of this project](CONTRIBUTING.md#java-language-formatting-guidelines)
- [x] I have rebased my changes on top of the latest master branch

- [x] I have made corresponding changes to the documentation
- [ ] ~~I have added tests that prove my fix is effective or that my feature works~~
- [ ] ~~New and existing [**unit** tests](https://github.com/elastic/apm-agent-java/blob/master/CONTRIBUTING.md#testing) pass locally with my changes~~

- [ ] ~~I have updated [CHANGELOG.asciidoc](CHANGELOG.asciidoc)~~
- [ ] ~~I have updated [supported-technologies.asciidoc](docs/supported-technologies.asciidoc)~~
- [ ] ~~Added an API method or config option? Document in which version this will be introduced~~
- [ ] ~~Added an instrumentation plugin? How did you make sure that old, non-supported versions are not instrumented by accident?~~

## Related issues

Closes #1041 
## Screenshots
<!-- _(Optional)_
Add here screenshots about how the project will be changed after the PR is applied. They could be related to web pages, terminal, etc, or any other image you consider important to be shared with the team.

### CODE REVIEW

**Comment by bmorelli25** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Comment by RajatArora08** [comment]
@bmorelli25 Thanks for the review! Can you help merge this? Or assign it to the appropriate person. Not sure who to assign this.

**Comment by bmorelli25** [comment]
Yup, I'll let one of the engineers merge this.

@felixbarny or @SylvainJuge What does the failing `CI-approved contributor` check mean?

**Comment by RajatArora08** [comment]
@bmorelli25 Thanks. Afaik, I had not signed the contributor agreement before I did the PR. Did it right after. Should be good now. Someone can review that.

**Comment by felixbarny** [comment]
thanks!

**Pull request merged**
