### PR TITLE
support Spring AMQP's SimpleMessageListenerContainer

### LINKED ISSUE #1635: RabbitMQ follow up: support Spring AMQP's SimpleMessageListenerContainer
See also https://github.com/elastic/apm-agent-java/pull/1328#issuecomment-769186851

### PR DESCRIPTION
**Pull request by kananindzya**
closes #1635 

## Checklist

- [X] This is an enhancement of existing features, or a new feature in existing plugins
  - [X] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)
  - [X] I have added tests that prove my fix is effective or that my feature works
  - [ ] Added an API method or config option? Document in which version this will be introduced
  - [ ] I have made corresponding changes to the documentation
- [ ] This is a bugfix
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)
  - [ ] I have added tests that would fail without this fix
- [ ] This is a new plugin
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)
  - [ ] My code follows the [style guidelines of this project](https://github.com/elastic/apm-agent-java/blob/master/CONTRIBUTING.md#java-language-formatting-guidelines)
  - [ ] I have made corresponding changes to the documentation
  - [ ] I have added tests that prove my fix is effective or that my feature works
  - [ ] New and existing [**unit** tests](https://github.com/elastic/apm-agent-java/blob/master/CONTRIBUTING.md#testing) pass locally with my changes
  - [ ] I have updated [supported-technologies.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/docs/supported-technologies.asciidoc)
  - [ ] Added an API method or config option? Document in which version this will be introduced
  - [ ] Added an instrumentation plugin? Describe how you made sure that old, non-supported versions are not instrumented by accident.
- [ ] This is something else
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)

### CODE REVIEW

**Comment by kananindzya** [comment]
Hi @eyalkoren , @felixbarny 
Please review this PR

**Comment by kananindzya** [comment]
image

image

**Comment by eyalkoren** [comment]
@kananindzya I finally got to this PR. You did great job! 👏  

I started by just rearranging modules - since you already added a module for the tests, I moved all instrumentation code to it, leaving the base RabbitMQ module nondependent in Spring in any way. 
I'll submit a review shortly.

Thanks for your invaluable contribution!! 🙏

**Comment by eyalkoren** [comment]
@kananindzya well done!! 
I did some additional minor changes and this part is ready.

What about supporting the batch API - `org.springframework.amqp.core.MessageListener#onMessageBatch`? I assume it will require similar approach to what we did with Kafka - starting/activating/deactivating/ending transactions during the iteration over the message batch. See https://github.com/elastic/apm-agent-java/blob/master/apm-agent-plugins/apm-kafka-plugin/apm-kafka-headers-plugin/src/main/java/co/elastic/apm/agent/kafka/helper/ConsumerRecordsIteratorWrapper.java.
It may require some effort, so makes sense to handle within a separate PR. WDYT?

**Review by eyalkoren — APPROVED** [review]

**Review by eyalkoren — COMMENTED** [review]
As per [the spec](https://github.com/elastic/apm/blob/master/specs/agents/tracing-instrumentation-messaging.md#-rabbitmq-naming-specifics), the default exchange in RabbitMQ is represented by an empty string, which we want to replace with `<default>`. The Spring AMQP module should make use of the `co.elastic.apm.agent.rabbitmq.AbstractBaseInstrumentation#normalizeExchangeName` method for that.
@kananindzya, if you have a test case that uses the default exchange, please add it and I will add the required change.

**Comment by kananindzya** [comment]
> As per [the spec](https://github.com/elastic/apm/blob/master/specs/agents/tracing-instrumentation-messaging.md#-rabbitmq-naming-specifics), the default exchange in RabbitMQ is represented by an empty string, which we want to replace with `<default>`. The Spring AMQP module should make use of the `co.elastic.apm.agent.rabbitmq.AbstractBaseInstrumentation#normalizeExchangeName` method for that.
> @kananindzya, if you have a test case that uses the default exchange, please add it and I will add the required change.

please check new test

**Pull request merged**
