### PR TITLE
docs: update config precedence and add dynamic badge

### PR DESCRIPTION
**Pull request by bmorelli25**
## What does this PR do?
This PR moves the configuration precedence information to a table and adds badges for dynamic configuration. The dynamic badges are links to the `=== Dynamic configuration` section heading.

## Related issues
Closes https://github.com/elastic/apm-agent-java/issues/1104.
For https://github.com/elastic/observability-dev/issues/639.

## Screenshots
Screen Shot 2020-04-06 at 2 58 56 PM

### CODE REVIEW

**Comment by bmorelli25** [comment]
Badges for dynamic config were added after the `${option.description}`. Do we want to rename the badge from `dynamic` to `reloadable`?

**Comment by bmorelli25** [comment]
We could also swap configs to horizontal tables. They do take up a bit more room, but maybe with a collapsible option, that's OK? How do you feel about this:

java-settins-tables

**Comment by bmorelli25** [comment]
Please note that I'm not sure why the preview and my screenshots above are not showing a border around the collapsible sections. See this comment for a realistic visual: https://github.com/elastic/docs/pull/1794#issuecomment-609864528

**Comment by bmorelli25** [comment]
One other option. Keep Default / Type / Dynamic in a table. Move Java System Properties, Property file, and Environment into a collapsible section that defaults to closed.

**Comment by SylvainJuge** [comment]
I really like the `Dynamic` badge, it's really clear and understandable.

Regarding configuration options, I feel that
- tables (especially without borders) don't really fit long strings like our option names
- using a collapsible option might help to save some space here, especially with the vertical layout
- the `> Properties of xxxx` could be replaced with `> xxxxxx (default_value)`, which allows to have something useful even when collapsed.
- what about adding the whole option description to the collapsible part ? that means that our reference configuration page will be mostly a list of all available options ?

**Comment by bmorelli25** [comment]
Thanks for the feedback @SylvainJuge!

> the > Properties of xxxx could be replaced with > xxxxxx (default_value), which allows to have something useful even when collapsed.

I like the thought, but I don't think that adding the default to the drop-down will work. Some of the configurations have very long defaults, e.g., https://www.elastic.co/guide/en/apm/agent/java/master/config-core.html#config-sanitize-field-names. I tried adding the type to the drop-down, but it looks funky to me:

Screen Shot 2020-04-13 at 10 21 43 AM

> using a collapsible option might help to save some space here, especially with the vertical layout

> what about adding the whole option description to the collapsible part ? that means that our reference configuration page will be mostly a list of all available options ?

Yeah, the goal with the collapsible block was to save space. But the more I think about it, the configuration options should be expanded by default. If we collapse everything, I worry we'll make it harder for users who typically `ctrl + f` the docs.

I'm going to remove the collapsible sections from this PR. I don't think we have the right tooling to make these changes yet.

**Pull request merged**
