### PR TITLE
spring webflux & reactor netty plugins

### PR DESCRIPTION
**Pull request by PGoski**
I've improved #827 and made apm-spring-weblux to work with real life app, added netty support also:

java agent jar for testing:
https://github.com/PGoski/apm-agent-java/releases/tag/1.16.1-SNAPSHOT

Tested with Spring Boot 2.2.2.RELEASE

With Netty:
```
<dependency>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-starter-webflux</artifactId>
</dependency>
```

Tomcat:
```
                   <dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webflux</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-reactor-netty</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-tomcat</artifactId>
		</dependency>
```
       
## Checklist          
- [ ] My code follows the [style guidelines of this project](https://github.com/elastic/apm-agent-java/blob/master/CONTRIBUTING.md#java-language-formatting-guidelines)
- ~[ ] I have made corresponding changes to the documentation~
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing [**unit** tests](https://github.com/elastic/apm-agent-java/blob/master/CONTRIBUTING.md#testing) pass locally with my changes
- [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)
- [ ] I have updated [supported-technologies.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/docs/supported-technologies.asciidoc)
- ~[ ] Added an API method or config option? Document in which version this will be introduced~
- [ ] Added an instrumentation plugin? Describe wow you made sure that old, non-supported versions are not instrumented by accident.

My goal was to implement for Spring Boot 2.2.2.RELEASE, tried to keep injection logic as lightweight as possible and I don't guarantee that some older versions are working. However tried to set Spring Boot version to a lower number in pom and tests passed, which is a good sign.

### CODE REVIEW

**Comment by felixbarny** [comment]
Epic! Thanks a lot for your PR!
We have limited bandwidth at the moment but Spring WebFlux is a priority for us. I hope we'll be able to give this a review soon.

Any area you specifically want to have feedback on? Are you running this in production or staging environments or plan to do it soon? I've messed up the PR templates, but could I ask you to fill out this one: https://github.com/elastic/apm-agent-java/blob/master/.github/PULL_REQUEST_TEMPLATE/new_plugin.md?

Is the PR feature complete or do you want to implement anything else before this can be merged?

Does this PR only work with Netty or also Undertow and Tomcat?

Thanks a lot 🙏

**Comment by PGoski** [comment]
Update: I've implemented a better integration with webflux + netty with transaction grouping and error capture in my last commit

elastic agent jar for testing: https://github.com/PGoski/apm-agent-java/releases/tag/1.16.1-SNAPSHOT-2

> Any area you specifically want to have feedback on? 

Would be great to get a good code review :)

>Are you running this in production or staging environments or plan to do it soon?

Currently I am evaluating in staging environment (spring webflux + netty) and planning deploy it to prod by the end of this week.

> Is the PR feature complete or do you want to implement anything else before this can be merged?

For MVP it is enough.

> Does this PR only work with Netty or also Undertow and Tomcat?

I've tested on Netty and Tomcat, results are the same

 >I've messed up the PR templates, but could I ask you to fill out this one: https://github.com/elastic/apm-agent-java/blob/master/.github/PULL_REQUEST_TEMPLATE/new_plugin.md?

Here is additional context about PR

>My code follows the style guidelines of this project

404 in the link

>I have made corresponding changes to the documentation

what documentation

> I have added tests that prove my fix is effective or that my feature works

Additional tests for Netty  are needed

> New and existing unit tests pass locally with my changes

I've touched apm-spring-webflux-plugin only, tests there pass

> I have updated CHANGELOG.asciidoc

no

> I have updated supported-technologies.asciidoc

no

>  Added an API method or config option? Document in which version this will be introduced

no

> Added an instrumentation plugin? Describe wow you made sure that old, non-supported versions are not instrumented by accident.

My goal was to implement for Spring Boot 2.2.2.RELEASE, tried to keep injection logic as lightweight as possible and I don't guarantee that some older versions are working. However tried to set Spring Boot version to a lower number in pom and tests passed, which is a good sign.

P.S. remembered good old days when I was JRebel dev and such tasks were my daily duties :)

**Comment by felixbarny** [comment]
I've edited the PR description and added the checkboxes. Links are fixed.

**Comment by felixbarny** [comment]
@SylvainJuge has also investigated instrumenting WebFlux. We'll reconcile the approaches and see how to best move forward.

I'm currently learning about the inner workings of WebFlux by debugging through your tests, very helpful 🙂

**Comment by PGoski** [comment]
the plugin is running in the production for 5 days now, so far so good

**Comment by SylvainJuge** [comment]
FYI I am currently working on making this PR merge properly with my initial work on the subject.

As there are numerous changes required, it will be easier to open another PR on your branch directly.

Please don't refactor everything until it's open (might take a few days as I have limited availability right now).

**Comment by PGoski** [comment]
Sure, np

**Comment by dengliming** [comment]
@PGoski  Can you please also add support webclient? This PR looks like only support the server side.

**Comment by PGoski** [comment]
> @PGoski Can you please also add support webclient? This PR looks like only support the server side.

Unfortunately don't have time for it in the near future

**Comment by dengliming** [comment]
> > @PGoski Can you please also add support webclient? This PR looks like only support the server side.
> 
> Unfortunately don't have time for it in the near future

I can develop client-side support. Maybe I can create a new PR. What is the progress of this PR？@PGoski @SylvainJuge SylvainJuge

**Comment by SylvainJuge** [comment]
Quick update on the topic, I've been able to make good progress on it this week.

I've opened a draft PR on @PGoski PR (https://github.com/PGoski/apm-agent-java/pull/2), while not ready for prime time, it's definitely going forward. I'll provide a detailed checklist of what is left to do next week.

**Comment by SylvainJuge** [comment]
As there was a very large number of changes since I started working on this, it is simpler to open another PR (#1305) rather than updating this one. Existing code has been modified and extended a lot, but was nonetheless definitely helpful, especially for the test suite.

This new PR covers Webflux server, not the client.
The Webflux client instrumentation will be covered with a separate issue #1306

As a result:
- This PR will be closed and is supersed with #1305, feel free to send any feedback you may have as a PR comment
- the draft PR I opened previously on @PGoski repository will be closed (https://github.com/PGoski/apm-agent-java/pull/2)

**Pull request closed without merging**
