### PR TITLE
Exclude Quartz 1 from instrumentation

### PR DESCRIPTION
**Pull request by felixbarny**
To avoid IncompatibleClassChangeError: Found class org.quartz.JobExecutionContext, but interface was expected

### CODE REVIEW

**Comment by SylvainJuge** [comment]
Quartz 1.8.x is about 7 to 8 years old, what would it cost to provide a compatible instrumentation for it ? Is there any issue with binary compatibility where we expect it to be an interface in 2.x versions and it was a class in older version ?

**Comment by felixbarny** [comment]
> Quartz 1.8.x is about 7 to 8 years old, what would it cost to provide a compatible instrumentation for it ?

We'd have to have another module compiled against Quartz 1.8.
I'd wait for user requests to do that. It shouldn't be hard but if no one uses it anyway it's probably not a good use of time to implement that.

> Is there any issue with binary compatibility where we expect it to be an interface in 2.x versions and it was a class in older version ?

Correct. As we compile against the interface and at runtime, it's a class the JVM bails out.

**Comment by eyalkoren** [comment]
> Correct. As we compile against the interface and at runtime, it's a class the JVM bails out.

Ahh, I wondered why it failed, so BB adds an `invokeinterface` instruction while it needs to be `invokevirtual`/`invokespecial`?

**Comment by felixbarny** [comment]
That is not Byte Buddy's fault. Byte Buddy takes the advice method as a template and inlines it into the instrumented method. The `javac` compiler does the `INVOKEINTERFACE` call. See also the byte code for the relevant method:

https://github.com/elastic/apm-agent-java/blob/96b7d60e4edcb39242ab5d7922111d52fd9c1023/apm-agent-plugins/apm-quartz-job-plugin/src/main/java/co/elastic/apm/agent/quartz/job/JobTransactionNameAdvice.java#L59-L61

```
L14
    LINENUMBER 59 L14
    ALOAD 3
    ALOAD 0
    INVOKEINTERFACE org/quartz/JobExecutionContext.getJobDetail ()Lorg/quartz/JobDetail; (itf)
    INVOKEINTERFACE org/quartz/JobDetail.getKey ()Lorg/quartz/JobKey; (itf)
    INVOKEVIRTUAL org/quartz/JobKey.toString ()Ljava/lang/String;
    INVOKEVIRTUAL co/elastic/apm/agent/impl/transaction/Transaction.withName (Ljava/lang/String;)Lco/elastic/apm/agent/impl/transaction/AbstractSpan;
    CHECKCAST co/elastic/apm/agent/impl/transaction/Transaction
    LDC "scheduled"
```

**Comment by eyalkoren** [comment]
Of course it's not Byte Buddy's fault, it's ours by compiling against an interface, there is no blaming here 🙂 
However, it is the one adding the instructions in practice...

**Pull request merged**
