### PR TITLE
Service name discovery based on webapp manifest

### PR DESCRIPTION
**Pull request by felixbarny**
## What does this PR do?
Discovers the service name based on `servletContext.getResource("/META-INF/MANIFEST.MF")`

- [x] Servlet::service
- [x] Servlet::init
- [x] Filter::doFilter
- [x] Filter::init

Open questions
- What happens if the web application archive doesn't have a `/META-INF/MANIFEST.MF`? Does `servletContext.getResource("/META-INF/MANIFEST.MF")` return the manifest of a jar in the `lib` directory?

## Checklist

- [x] This is an enhancement of existing features, or a new feature in existing plugins
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/main/CHANGELOG.asciidoc)
  - [x] I have added tests that prove my fix is effective or that my feature works
  - [ ] Added an API method or config option? Document in which version this will be introduced
  - [ ] I have made corresponding changes to the documentation
- [ ] This is a bugfix
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/main/CHANGELOG.asciidoc)
  - [ ] I have added tests that would fail without this fix
- [ ] This is a new plugin
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/main/CHANGELOG.asciidoc)
  - [ ] My code follows the [style guidelines of this project](https://github.com/elastic/apm-agent-java/blob/main/CONTRIBUTING.md#java-language-formatting-guidelines)
  - [ ] I have made corresponding changes to the documentation
  - [ ] I have added tests that prove my fix is effective or that my feature works
  - [ ] New and existing [**unit** tests](https://github.com/elastic/apm-agent-java/blob/main/CONTRIBUTING.md#testing) pass locally with my changes
  - [ ] I have updated [supported-technologies.asciidoc](https://github.com/elastic/apm-agent-java/blob/main/docs/supported-technologies.asciidoc)
  - [ ] Added an API method or config option? Document in which version this will be introduced
  - [ ] Added an instrumentation plugin? Describe how you made sure that old, non-supported versions are not instrumented by accident.
- [ ] This is something else
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/main/CHANGELOG.asciidoc)

cc @tobiasstadler

### CODE REVIEW

**Comment by felixbarny** [comment]
@tobiasstadler would you be able to try this out?

**Comment by tobiasstadler** [comment]
Sure, should I test anything specific?

**Comment by felixbarny** [comment]
I'd appreciate feedback on these scenarios in particular:
* Test whether the detection for multiple Webapps on the same container works as expected
* Is the `Filter::init` and `Servlet::init` instrumentation a good enough alternative to the approach you proposed earlier that involved container-specific hooks?
* What happens if the web application archive doesn't have a `/META-INF/MANIFEST.MF`? Does `servletContext.getResource("/META-INF/MANIFEST.MF")` return the manifest of a jar in the lib directory?
* General feedback on the code, if you have any

**Comment by felixbarny** [comment]
I've added integration tests and they're passing now 🎉 

> What happens if the web application archive doesn't have a `/META-INF/MANIFEST.MF`? Does `servletContext.getResource("/META-INF/MANIFEST.MF")` return the manifest of a jar in the lib directory?

The `/META-INF/MANIFEST.MF` file gets created even if users don't add the `Implementation-Title` and `Implementation-Version` manifest entries. When you purposefully delete the manifest file, `servletContext.getResource("/META-INF/MANIFEST.MF")` returns `null`, not a random manifest file from a jar in the `WEB-INF/lib` dir.

**Comment by felixbarny** [comment]
This is how to properly set the manifest entries so that the agent can discover the `service.name` and `service.version`:

```xml
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <!-- uncomment if you're building a jar
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.2.2</version>
                -->
                <!-- uncomment if you're building a war
                <artifactId>maven-war-plugin</artifactId>
                <version>3.3.2</version>
                -->
                <configuration>
                    <archive>
                        <!-- Adds
                        Implementation-Title based on ${project.name} and
                        Implementation-Version based on ${project.version}
                        -->
                        <manifest>
                            <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
                        </manifest>
                        <!-- To customize the Implementation-* entries, remove addDefaultImplementationEntries and add them manually
                        <manifestEntries>
                            <Implementation-Title>foo</Implementation-Title>
                            <Implementation-Version>4.2.0</Implementation-Version>
                        </manifestEntries>
                        -->
                    </archive>
                </configuration>
            </plugin>
        </plugins>
    </build>
```

**Comment by felixbarny** [comment]
@SylvainJuge review hints: Start with  `ServletServiceNameHelper`, `ServiceInfo`, and `InitServiceNameInstrumentation`. The rest is really just moving things around.

**Review by SylvainJuge — APPROVED** [review]
LGTM, changed a few bits for proper coverage of ServiceInfo

**Comment by tobiasstadler** [comment]
> @tobiasstadler would you be able to try this out?

It will look at it it on the weekend

**Comment by tobiasstadler** [comment]
Here are my results on JBoss EAP:
* My JAX-RS applications mostly work. `org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher#init` is called during deployment and uses the Manifest (if available and the Servlet Context Name otherwise) to set the service name. However sometimes `javax.ejb.Schedule` transactions have the "wrong" service name as they are started before the `init` method of any servlet is called (but subsequent invocations will have the correct service name)
* My Struts applications do not really work because no `init` method is called before any request is received. But during the first request the service name is configured correctly. Maybe instrumenting `javax.servlet.ServletContextListener#contextInitialized` (and the JakartaEE equivalent) can help determining the "correct" service name earlier.
* My JMS applications also do not work as no `init` method is ever called.

I have one application that uses Spark Java which (ab)uses Servlet Filters. Fortunately `FilterConfig` is `null` when `javax.servlet.Filter#init` is called, so the service name is not falsely overwritten.

Overall I think it is an improvement, but not the way I would like it to be. So I will stay with my customer WildFly/JBoss instrumentation at the moment.

**Comment by tobiasstadler** [comment]
@felixbarny I implemented `ServletContextListener#contextInitialized` instrumentation in #2443

**Comment by tobiasstadler** [comment]
@felixbarny I implemented `ServletContainerInitializer#onStartup` instrumentation in #2449

**Pull request merged**
