### PR TITLE
Instrument javax.servlet.Filter the same way as javax.servlet.FilterChain (#1857)

### LINKED ISSUE #1857: Support for javax.servlet.Filter
## Is your feature request related to a problem?
Standalone Spark (https://sparkjava.com) uses Filters without a FilterChain (see https://github.com/perwendel/spark/blob/54079b0f95f0076dd3c440e1255a7d449d9489f1/src/main/java/spark/embeddedserver/jetty/JettyHandler.java#L50), so no transaction is started by agent.

## Describe the solution you'd like
`javax.servlet.Filter` should be instrumented in the same way as `javax.servlet.FilterChain`

## Describe alternatives you've considered
Manually starting the transaction

### PR DESCRIPTION
**Pull request by tobiasstadler**
## What does this PR do?
Fixes #1857

## Checklist

- [x] This is an enhancement of existing features, or a new feature in existing plugins
  - [x] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)
  - [x] I have added tests that prove my fix is effective or that my feature works
  - [ ] Added an API method or config option? Document in which version this will be introduced
  - [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by tobiasstadler** [comment]
Can somebody please do a review?

**Review by SylvainJuge — APPROVED** [review]

**Comment by tobiasstadler** [comment]
@SylvainJuge I merged the master branch (which disabled the auto-merge), would you mind merging it?

**Comment by eyalkoren** [comment]
@SylvainJuge this may considerably increase the number of times `ServletApiAdvice` can be invoked. Do you think we should add a quick abort when not required? For example - if there is an active transaction when `ServletApiAdvice#onEnterServletService()` starts - abort early; also make sure `ServletApiAdvice#onExitServletService()` aborts early when not required (e.g. when `onEnterServletService` aborted).

**Comment by tobiasstadler** [comment]
@eyalkoren Something like
```
ElasticApmTracer tracer = GlobalTracer.getTracerImpl();
if(tracer == null || tracer.currentTransaction() != null) {
    return null;
}
```

**Comment by SylvainJuge** [comment]
I did run a few wall-clock benchmarks with & without this change and did not found significant impact.

I did test with Tomcat though, which means that the `ApplicationFilterChain` is a parent of any call to `Filter.doFilter` configured within the application, hence making the Advice exit early as the transaction scope is defined by `ApplicationFilterChain` which extends `FilterChain` (but that might be an implementation detail only for Tomcat`.

Alternatively, for the specific case of Spark, the usage of `Servlet` API is quite non-standard, and maybe adding a proper support for Jetty handler to handle the transaction would also work (albeit it's definitely a bit more work).

**Comment by tobiasstadler** [comment]
@SylvainJuge It is the same for Undertow (But `ApplicationFilterChain` is called `FilterChainImpl`)

**Comment by tobiasstadler** [comment]
So how should we proceed?

**Comment by tobiasstadler** [comment]
Thank You!

**Pull request merged**
