### PR TITLE
Adding support for the new mongodb-driver-sync library

### LINKED ISSUE #1547: Add support for MongoDB 4.x synchronous/legacy driver
Initially reported [in our forum](https://discuss.elastic.co/t/mongo-driver-4-x-is-not-supported-on-java/248571)

Our current support for MongoDB is limited to 3.x version of the driver.

https://mongodb.github.io/mongo-java-driver/4.1/driver/getting-started/installation/

There are two variants of the driver to support:
- `mongo-driver-sync`
- `mongodb-driver-legacy` (probably close to 3.x driver)

Driver/Server [Compatibility matrix](https://docs.mongodb.com/drivers/java#compatibility)

Also, there is also a newer streams-based driver that should probably be covered with a separate implementation issue.
https://mongodb.github.io/mongo-java-driver/4.1/driver-reactive/

-----
EDIT: As mentioned in the comments below, there is also another variant for which we might have to check or add proper support: https://mvnrepository.com/artifact/org.mongodb/mongodb-driver-core

### PR DESCRIPTION
**Pull request by juliovalcarcel**
This starts to address #1547 and more specifically enables the new mongodb-driver-sync to work with Spring Boot's MongoDB starter by default. I did this by following what was done for Cassandra and splitting mongoclient into a v3 and a v4 package. The v4 package is setup to start using the mongodb-driver-sync dependency and is updated to use the new classes.

I am having problems with the MongoDriverSyncInstrumentationIT and getting it to run without falling, but all unit tests passed (Just duplicated currently from v3 with minor tweaks). I could use some help from someone on what needs to be revised for the IT and then I will add additional versions to the IT. 

There is definitely room for deduplication between the v3 and v4 drivers but I wanted to get a working version up and running for feedback.

Updated checklist after feedback

## Checklist

- [ ] This is an enhancement of existing features, or a new feature in existing plugins
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)
  - [ ] I have added tests that prove my fix is effective or that my feature works
  - [ ] Added an API method or config option? Document in which version this will be introduced
  - [ ] I have made corresponding changes to the documentation
- [ ] This is a bugfix
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)
  - [ ] I have added tests that would fail without this fix
- [x] This is a new plugin
  - [x] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)
  - [x] My code follows the [style guidelines of this project](https://github.com/elastic/apm-agent-java/blob/master/CONTRIBUTING.md#java-language-formatting-guidelines)
  - [x] I have made corresponding changes to the documentation
  - [x] I have added tests that prove my fix is effective or that my feature works
  - [x] New and existing [**unit** tests](https://github.com/elastic/apm-agent-java/blob/master/CONTRIBUTING.md#testing) pass locally with my changes
  - [x] I have updated [supported-technologies.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/docs/supported-technologies.asciidoc)
  - [ ] Added an API method or config option? Document in which version this will be introduced
  - [x] Added an instrumentation plugin? Describe how you made sure that old, non-supported versions are not instrumented by accident.
- [ ] This is something else
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)

------
EDT: 
Closes #1547

### CODE REVIEW

**Comment by kananindzya** [comment]
> MongoDriverSyncInstrumentationIT

Hi, @juliovalcarcel 
As Felix noted in the `co.elastic.apm.agent.mongoclient3.ConnectionInstrumentation` comment, in version 4 everything works via 'com.mongodb.internal.connection.Connection#command'.
Therefore, in version 4, 'Connection Instrumentation' is irrelevant. 
And you need instrument only with `ConnectionCommandInstrumentation`.
For this you need to change the 'getTypeMatcher()' in `MongoDriverInstrumentation`, since in version 4 `Connection` moved to other package `com.mongodb.internal.connection`.
```
    @Override
    public ElementMatcher<? super TypeDescription> getTypeMatcher() {
        return nameStartsWith("com.mongodb.internal")
            .and(hasSuperType(named("com.mongodb.internal.connection.Connection")));
    }
```
And also now `command` takes `String` as the first argument. So in `ConnectionAdvice` no need checking type of the 0 argument.

**Comment by juliovalcarcel** [comment]
@kananindzya Thank you for the feedback and sorry for the delay in response but I have rebased my branch onto main and fixed the issues you found as well as fixed both tests. Included are tests for all current minor 4.x versions. Please let me know if there are any additional fixes that you see need to be made and I will try to get to them much quicker.

**Comment by juliovalcarcel** [comment]
I wanted to check and see if there was a plan to review/merge this? Or should I wait to rebase it and fix the conficts?

**Comment by SylvainJuge** [comment]
Hi @juliovalcarcel we have added this to our short-term backlog, thus we expect to be able to handle it soon (but can't guarantee any precise ETA as unexpected priorities tend to get the last word).

**Comment by juliovalcarcel** [comment]
@SylvainJuge okay, I will work to rebase it and will keep an eye out for any comments to keep it moving forward. Thanks!

**Comment by juliovalcarcel** [comment]
Branch has been rebased on my end. Please let me know what feedback there is and I will resolve it ASAP.

**Comment by SylvainJuge** [comment]
Quick update: I have pushed my changes to this branch so the original contributions of @juliovalcarcel are still there even if slightly altered and this PR should now be closer to be merged. My approval is only to allow running in CI for now.

**Review by SylvainJuge — APPROVED** [review]
Approving to allow running in CI.

**Comment by juliovalcarcel** [comment]
@SylvainJuge you let me know how I should help. Sorry for the delay, I was on vacation and just got back. I am okay with all the approaches but am all good with the blind trust :)

**Comment by SylvainJuge** [comment]
@juliovalcarcel I've merged the changes in this PR branch, thus I've closed the humongous "trust me I know what I do" PR.
So, code-wise there isn't much left to do, but it would be more than welcome if you could try [this snapshot](https://apm-ci.elastic.co/job/apm-agent-java/job/apm-agent-java-mbp/job/PR-2241/59/artifact/src/github.com/elastic/apm-agent-java/elastic-apm-agent/target/elastic-apm-agent-1.33.1-SNAPSHOT.jar) to make sure that it works in your setup, not being very familiar with MongoDB API there might be a few cases that aren't properly covered.

**Comment by SylvainJuge** [comment]
@elasticmachine run elasticsearch-ci/docs

**Review by jackshirazi — APPROVED** [review]

**Comment by SylvainJuge** [comment]
@elasticmachine run elasticsearch-ci/docs

**Pull request merged**
