### PR TITLE
Use temp properties file instead of providing agent arguments

### LINKED ISSUE #864: Segmentation fault when attaching apm-agent-java to adopt jdk 11
**Describe the bug**
When attaching apm-agent-java through the apm-agent-attach dependency, we are getting a segmantation fault and are unable to start our application

**To Reproduce**
Start spring-boot-2 application with adopt jdk 11, and attach agent using apm-agent-attach

**Expected behavior**
Everything should be working as expected

**Debug logs**

From hs_err_pid.log file

<details>
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00006769732d746b, pid=4732, tid=18292
#
# JRE version: OpenJDK Runtime Environment (11.0.4+11) (build 11.0.4+11)
# Java VM: OpenJDK 64-Bit Server VM (11.0.4+11, mixed mode, tiered, compressed oops, g1 gc, windows-amd64)
# Problematic frame:
# C  0x00006769732d746b
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   https://github.com/AdoptOpenJDK/openjdk-build/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  S U M M A R Y ------------

Command Line: -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:51638,suspend=y,server=n -XX:TieredStopAtLevel=1 -Xverify:none -Dspring.output.ansi.enabled=always -Dcom.sun.management.jmxremote -Dspring.jmx.enabled=true -Dspring.liveBeansView.mbeanDomain -Dspring.application.admin.enabled=true -javaagent:~.IntelliJIdea2019.1\system\groovyHotSwap\gragent.jar -javaagent:~.IntelliJIdea2019.1\system\captureAgent\debugger-agent.jar -Dfile.encoding=UTF-8 ApplicationKt

Host: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, 8 cores, 31G,  Windows 10 , 64 bit Build 15063 (10.0.15063.1805)
Time: Thu Sep 26 14:10:52 2019 W. Europe Daylight Time elapsed time: 69 seconds (0d 0h 1m 9s)

---------------  T H R E A D  ---------------

Current thread (0x00000214d534f000):  JavaThread "main" [_thread_in_native, id=18292, stack(0x0000006de7900000,0x0000006de7a00000)]

Stack: [0x0000006de7900000,0x0000006de7a00000],  sp=0x0000006de79fd960,  free space=1014k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  0x00006769732d746b

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  com.sun.jna.Native.invokePointer(Lcom/sun/jna/Function;JI[Ljava/lang/Object;)J+0

</details>

### PR DESCRIPTION
**Pull request by felixbarny**
closes #864

### Checklist

- [x] Implement code
- [x] Add tests
- [ ] ~Update documentation~
- [x] Update [CHANGELOG.md](CHANGELOG.md)
- [ ] ~Update [supported-technologies.asciidoc](docs/supported-technologies.asciidoc)~
- [ ] ~Added an API method or config option? Document in which version this will be introduced.~

### CODE REVIEW

**Comment by hcf** [comment]
Could it be possible to use system properties instead as suggested in the temporary fix for my problem? 

```
configuration.forEach((key, value) -> System.setProperty(String.format("elastic.apm.%s", key), value));
```

Not sure what is best for concurrency, conflicts, etc.

**Comment by felixbarny** [comment]
That wouldn't work with the external attachment (https://www.elastic.co/guide/en/apm/agent/java/current/setup-attach-cli.html). Do you see an issue with the proposed approach?

**Comment by hcf** [comment]
The only issue I can think about is what happens if we start multiple JVM on the same machine at the same time?

**Comment by felixbarny** [comment]
Then each JVM will get their own temporary file (with a random name) which gets deleted after the attachment for that JVM is completed.

**Pull request merged**
