### PR TITLE
Use `unknown-${service.agent.name}-service` instead of `my-service`

### LINKED ISSUE #2306: [META 571] Align on default service name
[issue details](https://github.com/elastic/apm/issues/571)

[issue details](https://github.com/elastic/apm/issues/572)

As defined in https://github.com/elastic/apm/pull/499, agents don't require users to configure the `service_name`. Ideally, the a descriptive value can be inferred form the application. But in some cases that's not possible. In these cases, agents must now align on the naming scheme for the default service name. This enables the UI to show inline help for services that it identifies as unnamed services based on the naming scheme.

### PR DESCRIPTION
**Pull request by tobiasstadler**
## What does this PR do?
Fixes #2306

## Checklist
- [x] This is something else
  - [x] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)

### CODE REVIEW

**Comment by tobiasstadler** [comment]
@eyalkoren Since the issue is assigned to you, would you please have a look?

**Review by SylvainJuge — APPROVED** [review]
LGTM, thanks for handling this @tobiasstadler !

**Comment by eyalkoren** [comment]
run elasticsearch-ci/docs

**Comment by tobiasstadler** [comment]
Thank You!

**Pull request merged**
