### PR TITLE
fix micrometer invalid double values

### PR DESCRIPTION
**Pull request by SylvainJuge**
## What does this PR do?

Micrometer plugin reports metrics through a dedicated JSON serialization code, and does not properly handle corner cases with gauges that can have values of `Double.NaN` or `Double.NEGATIVE_INFINITY`, as a result there are cases where metric sets are sent with strings as values instead of numbers, for example `-Infinity`.

Ideally in the future if we start to have multiple plugins that report metrics, we should probably provide an internal API for this so there is no duplication of code and potential issues.

## Checklist

- [x] This is a bugfix
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)
  - [x] I have added tests that would fail without this fix

### CODE REVIEW

**Review by felixbarny — APPROVED** [review]

**Review by eyalkoren — COMMENTED** [review]
Lots of other meters' APIs return `double` values, like timers `totalTime()` and even `count()`. Can these fail us as well?
Maybe this check should be moved to `MicrometerMeterRegistrySerializer#serializeValue()` that can return a `boolean` indicating if the value was added?

**Comment by SylvainJuge** [comment]
> Lots of other meters' APIs return `double` values, like timers `totalTime()` and even `count()`. Can these fail us as well?
> Maybe this check should be moved to `MicrometerMeterRegistrySerializer#serializeValue()` that can return a `boolean` indicating if the value was added?

I have checked implementation of those (at least the version we compile against for the micrometer plugin), and they default to zero, thus I assume it is mostly safe to do so. End-user provided sub-classes aren't really expected here as the instances are provided through a builder from micrometer framework.

**Comment by eyalkoren** [comment]
OK, we will fix more if required then

**Review by eyalkoren — APPROVED** [review]

**Comment by pkgonan** [comment]
@eyalkoren @felixbarny 
Hi, when do you expect release date this PR?
Perhaps 1.18.1 version.

Thank you.

**Comment by SylvainJuge** [comment]
Hi @pkgonan !
The next release isn't scheduled yet, thus make sure that you have subscribed to notifications.

In the mean time, you can use the [snapshot](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=co.elastic.apm&a=elastic-apm-agent&v=LATEST) that is built every day from master if required.

**Comment by pkgonan** [comment]
@SylvainJuge 
Thank you for your reply.

**Pull request merged**
