### PR TITLE
[APM-CI][Java] use local weblogic Docker image cached

### PR DESCRIPTION
**Pull request by kuisathaverat**
PR to check when the cache is ready, then we can merge it

related to https://github.com/elastic/apm-agent-java/pull/565 and https://github.com/elastic/apm-agent-java/pull/555

### CODE REVIEW

**Comment by felixbarny** [comment]
jenkins run the tests please

**Comment by kuisathaverat** [comment]
I just merge https://github.com/elastic/apm-agent-java/pull/565 so we have to wait at least a day to the change be in the packer images, it is sure that on Monday it should work 🤞

**Comment by kuisathaverat** [comment]
ok, the image is not pull to the packer images, I have to review it with the Infra team

**Comment by kuisathaverat** [comment]
doing other stuff I've detected that the last packer image was done at 2019-04-09T14:42:35Z, so it does not contain our change yet.

**Comment by jonahbull** [comment]
@kuisathaverat FWIW the apm-ci packer build keeps failing because it can't pull the `weblogic` image:
```
Error response from daemon: pull access denied for docker.elastic.co/observability-ci/weblogic, repository does not exist or may require 'docker login'
Retry 1/2 exited 1, retrying in 1 seconds...
Error response from daemon: pull access denied for docker.elastic.co/observability-ci/weblogic, repository does not exist or may require 'docker login'
Retry 2/2 exited 1, no more retries left.
```
Think you'll need to auth with the docker registry before pulling.

**Comment by kuisathaverat** [comment]
@jonahbull I've supposed that the packer process has credentials configured to access to our registry, Can I access to the Vault directly? How you resolved this kind of access at packer build time?

**Comment by jonahbull** [comment]
@kuisathaverat I'm not sure what kind of access to vault, etc. there is within the `packer_cache` script in terms of what environmental variables are available. I'm going to try to bring in @fatmcgav who created this magic and see if he's got some suggestions on the best way forward here.

**Comment by fatmcgav** [comment]
So I think we have a couple of options here... 

1. It's possible to setup the relevant Docker auth config as part of the image build using the [`docker_config`](https://github.com/elastic/infra/tree/master/ansible/roles/docker_config) Ansible role. 
This means that the images will effectively have hard-coded credentials for `docker.elastic.co`. 
2. Update the `packer_cache` script to login to `docker.elastic.co` as part of the script. 

I think 1. is a safe approach, as we've used it for other clusters already, so I'll get a PR raised for that shortly...

**Comment by fatmcgav** [comment]
So #11372 has been merged, and the master Packer builder job is running now... https://infra-ci.elastic.co/view/Packer/job/elastic+infra+master+packer-builder/345/

🤞 that this should build a shiny new `apm-ci` image :)

**Comment by felixbarny** [comment]
Yay, it worked ❤️

**Comment by kuisathaverat** [comment]
I've relaunched the CI, it has passes the first check so we are in a good place

**Comment by kuisathaverat** [comment]
It has finished OK, @felixbarny Could we merge it?

**Pull request merged**
