### PR TITLE
Exclude com.github.benmanes.caffeine.cache.BoundedLocalCache.PerformCleanupTask from context propagation

### PR DESCRIPTION
**Pull request by tobiasstadler**
## What does this PR do?
Excludes `com.github.benmanes.caffeine.cache.BoundedLocalCache.PerformCleanupTask` from context propagation

## Checklist
- [x] This is something else
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/main/CHANGELOG.asciidoc)

### CODE REVIEW

**Comment by SylvainJuge** [comment]
Hi @tobiasstadler,

Can you provide a bit more context on the underlying reason we need to exclude it from context-propagation here ? For example, does it leads to leaks, error/warning messages or unwanted context propagation behavior ?

**Comment by tobiasstadler** [comment]
We profiled our app and saw quite often the following stack trace:

```
   java.lang.Thread.State: BLOCKED (on object monitor)
	at co.elastic.apm.agent.bci.ElasticApmAgent.ensureInstrumented(ElasticApmAgent.java:746)
	- waiting to lock <0x0000000480366a08> (a java.lang.Class for co.elastic.apm.agent.bci.ElasticApmAgent)
	at co.elastic.apm.agent.bci.DynamicTransformerProviderImpl.ensureInstrumented(DynamicTransformerProviderImpl.java:30)
	at co.elastic.apm.agent.sdk.DynamicTransformer.ensureInstrumented(DynamicTransformer.java:52)
	at co.elastic.apm.agent.concurrent.JavaConcurrent.captureContext(JavaConcurrent.java:123)
	at co.elastic.apm.agent.concurrent.JavaConcurrent.withContext(JavaConcurrent.java:118)
	at co.elastic.apm.agent.concurrent.ExecutorInstrumentation$ExecutorRunnableInstrumentation$AdviceClass.onExecute(ExecutorInstrumentation.java:116)
	at java.lang.invoke.LambdaForm$DMH/1527641465.invokeStatic_LL_L(LambdaForm$DMH)
	at java.lang.invoke.LambdaForm$MH/970083781.linkToTargetMethod(LambdaForm$MH)
	at java.util.concurrent.ForkJoinPool.execute(ForkJoinPool.java:2641)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.scheduleDrainBuffers(BoundedLocalCache.java:1432)
        ...
```

**Comment by eyalkoren** [comment]
Thanks a lot @tobiasstadler !
It seems very reasonable to avoid instrumenting these cache management scheduled tasks, I'll merge it.

One additional question though - do you see this only during JVMs startup, or also when capturing stack traces of long running JVMs? The reason I ask is that if you follow the [`ensureInstrumented`](https://github.com/elastic/apm-agent-java/blob/main/apm-agent-core/src/main/java/co/elastic/apm/agent/bci/ElasticApmAgent.java#L742-L782) logic, you'd see that this lock should be accessed for each instrumented class only once (or very limited number of times in case of high contention) when the instrumentation is first applied. If you see that on long running JVMs, can you figure out what's not working here? Could those be dynamic task class instances?

**Review by eyalkoren — APPROVED** [review]

**Comment by eyalkoren** [comment]
run integration tests

**Comment by eyalkoren** [comment]
run elasticsearch-ci/docs

**Comment by tobiasstadler** [comment]
Thank You!

**Pull request merged**
