### PR TITLE
Move CI to Java 11

### PR DESCRIPTION
**Pull request by cachedout**
Move the pipeline to Java 11.

### CODE REVIEW

**Comment by felixbarny** [comment]
The other stages are still using Java 10. We'll also have to merge #1237 first so that the Javadoc task passes.

**Comment by felixbarny** [comment]
The Javadoc task fails. Could you merge master in your branch?

**Comment by felixbarny** [comment]
Do you know which exact Java 11 version is used?

**Comment by felixbarny** [comment]
It's 11.0.6

Found this out by looking at the logs of the unit tests:

```
INFO  co.elastic.apm.agent.configuration.StartupInfo - Starting Elastic APM (unknown version) as surefirebooter13075343209484251341 on Java 11.0.6 (Oracle Corporation) Linux 5.3.0-1026-gcp
```

**Comment by cachedout** [comment]
@felixbarny Do you want to investigate these smoke test failures or shall we go ahead with this merge?

**Comment by felixbarny** [comment]
That's a flaky test. The smoke tests use a different Java version as tests execute in Docker containers.

**Pull request merged**
