### PR TITLE
Fix some tests on Windows

### PR DESCRIPTION
**Pull request by SylvainJuge**
## What does this PR do?

Fix some test failures on Windows

## Checklist

- [x] `co.elastic.apm.agent.jul.reformatting.JulEcsReformattingHelperTest`
- [ ] ~~`co.elastic.apm.agent.log4j2.Log4j2_17_1InstrumentationTest`~~ DISABLED ON WINDOWS
- [ ] ~~`co.elastic.apm.agent.log4j2.Log4j2_6SInstrumentationTest`~~ DISABLED ON WINDOWS
- [x] `git-commit-id-maven-plugin` failure - not failing the build when the plugin fails

### CODE REVIEW

**Comment by eyalkoren** [comment]
@SylvainJuge I feel both of us together spent too much time on overcoming these Windows Server quirks just to enable the log4j2 tests, so I propose we just bail now and disable them on Windows.

I want to merge this PR, because there's now a `git-commit-id-maven-plugin` failure, for which I want to open an issue and it'll be better if I can link to a public CI failure.

**Comment by eyalkoren** [comment]
run integration tests

**Comment by SylvainJuge** [comment]
I agree with you @eyalkoren , I'm fine with disabling those tests on windows for now.

**Review by eyalkoren — APPROVED** [review]

**Comment by eyalkoren** [comment]
Opened an [issue](https://github.com/git-commit-id/git-commit-id-maven-plugin/issues/591) on the `git-commit-id-maven-plugin` repo as a followup.

**Pull request merged**
