### PR TITLE
Capture exceptions that are logged using the fatal log level.

### PR DESCRIPTION
**Pull request by tobiasstadler**
## Checklist
- [x] This is an enhancement of existing features, or a new feature in existing plugins
  - [x] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)
  - [x] I have added tests that prove my fix is effective or that my feature works
  - [ ] Added an API method or config option? Document in which version this will be introduced
  - [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by felixbarny — APPROVED** [review]

**Comment by tobiasstadler** [comment]
@felixbarny The tests are passing. Would you please merge the PR?

**Comment by tobiasstadler** [comment]
Thank You!

**Comment by felixbarny** [comment]
No, thank you! 🙂

**Pull request merged**
