### PR TITLE
Add error reporting API to tracer-api.

### PR DESCRIPTION
**Pull request by raphw**
This change adds an representation of `ErrorCapture` to the tracer API to avoid a dependency on the core module. To reduce complexity, errors are always reported on the current span. No plugin derives from this practice what makes this sensible.

### CODE REVIEW

**Comment by v1v** [comment]
@mergifyio update

**Comment by raphw** [comment]
Force pushed with new hash to trigger new build which failed due to low memory on testcontainers.

**Review by JonasKunz — APPROVED** [review]
LGTM, I've done the rebase and just added two missing `@Override` annotations.

**Comment by JonasKunz** [comment]
run elasticsearch-ci/docs

**Pull request merged**
