### PR TITLE
Do not instrument proxies (#1735)

### LINKED ISSUE #1735: Proxy classes should not be instrumented
## Is your feature request related to a problem?
I want to "instrument" an EJB using `CaptureSpan`:
```
@Stateful
public class MyBean {
    @CaptureSpan
    public void doSomething() {}
}
```

However the name of the span is not 'MyBean#doSomething', but 'view123#doSomething', beause the span is started by the proxy class.

## Describe the solution you'd like
Proxy classes should not be instrumented

### PR DESCRIPTION
**Pull request by tobiasstadler**
## What does this PR do?
Fixes #1735

## Checklist
- [ ] This is an enhancement of existing features, or a new feature in existing plugins
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)
  - [ ] I have added tests that prove my fix is effective or that my feature works
  - [ ] Added an API method or config option? Document in which version this will be introduced
  - [ ] I have made corresponding changes to the documentation
- [x] This is a bugfix
  - [x] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)
  - [ ] ~I have added tests that would fail without this fix~
- [ ] This is a new plugin
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)
  - [ ] My code follows the [style guidelines of this project](https://github.com/elastic/apm-agent-java/blob/master/CONTRIBUTING.md#java-language-formatting-guidelines)
  - [ ] I have made corresponding changes to the documentation
  - [ ] I have added tests that prove my fix is effective or that my feature works
  - [ ] New and existing [**unit** tests](https://github.com/elastic/apm-agent-java/blob/master/CONTRIBUTING.md#testing) pass locally with my changes
  - [ ] I have updated [supported-technologies.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/docs/supported-technologies.asciidoc)
  - [ ] Added an API method or config option? Document in which version this will be introduced
  - [ ] Added an instrumentation plugin? Describe how you made sure that old, non-supported versions are not instrumented by accident.
- [ ] This is something else
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)

### CODE REVIEW

**Comment by tobiasstadler** [comment]
I would consider this a breaking change. If you agree/disagree I will update the changeling accordingly.

**Review by SylvainJuge — APPROVED** [review]

**Comment by SylvainJuge** [comment]
jenkins run the tests please

**Comment by SylvainJuge** [comment]
After discussing this internally we agreed that it should not really be a breaking change as it mostly impacts transaction/span naming. Also, it's very unlikely that there would be any strong dependency on current names as those are mostly generated at runtime, and thus might not be stable over time.

Thanks a lot for raising this issue @tobiasstadler !

**Comment by tobiasstadler** [comment]
Thank you!

**Pull request merged**
