### PR TITLE
Add instrumentation excludes for common APM vendors

### PR DESCRIPTION
**Pull request by felixbarny**

### CODE REVIEW

**Comment by SylvainJuge** [comment]
should also add `com.compuware` as suggested in #1037

**Comment by SylvainJuge** [comment]
And also `io.sqreen` might also make sense, even if it's not an APM, it is more likely to be used with another agent.

**Comment by WassimDhib** [comment]
also com.appdynamics.

**Comment by SylvainJuge** [comment]
Also, "com.singularity" which used to be the package used previously by
AppDynamics, there are still some references to it on their support forum:
https://community.appdynamics.com/t5/Java-Java-Agent-Installation-JVM/java-lang-NoClassDefFoundError-com-singularity-ee-agent-appagent/td-p/29468

**Comment by felixbarny** [comment]
I have already added `com.singularity`, I don't think there's a `com.appdynamics` package.

**Pull request merged**
