### PR TITLE
pom: bump opentelemetry-extension 1.10.0

### PR DESCRIPTION
**Pull request by v1v**
## What does this PR do?

Bump dependency to pick up the latest updates for the integration in the CI with the opentelemetry extension for the maven builds.

## Features

*opentelemetry-maven-extension `1.10.0`*

- Support Maven parallel builds(https://github.com/open-telemetry/opentelemetry-java-contrib/pull/161)
- Capture details on mojo goal executions: deploy:deploy, spring-boot:build-image, jib:build, snyk:test, snyk:monitor(https://github.com/open-telemetry/opentelemetry-java-contrib/pull/146)
- Fix lifecycle to support the Maven daemon(https://github.com/open-telemetry/opentelemetry-java-contrib/pull/169)
- Fix service.name attribute overwrite(https://github.com/open-telemetry/opentelemetry-java-contrib/pull/184)
- Fix default service.name + simplify configuration using Otel AutoConfig SDK 1.10 ResourceProvider SPI improvements (enable specifying the classloader making it compatible with Maven Plexus)(https://github.com/open-telemetry/opentelemetry-java-contrib/pull/187)
- Add Tracer instrumentationVersion (ie otel.library.version)(https://github.com/open-telemetry/opentelemetry-java-contrib/pull/191)
- Reduce the cardinality of mojo span names(https://github.com/open-telemetry/opentelemetry-java-contrib/pull/192)

*opentelemetry-maven-extension `1.9.0`*

- [Maven Extension] Update README, bump version to 1.7.0-alpha by @cyrille-leclerc in https://github.com/open-telemetry/opentelemetry-java-contrib/pull/129
- [Maven-Extension] Use Auto Configure Otel SDK Builder by @cyrille-leclerc in https://github.com/open-telemetry/opentelemetry-java-contrib/pull/132

### CODE REVIEW

**Review by eyalkoren — APPROVED** [review]

**Comment by v1v** [comment]
@cyrille-leclerc , are you aware of any breaking changes between `1.7` and `1.11`? I don't see any traces but there are traces with `1.7`, for instance:

- The latest build in the `main` branch produced traces, see [here](https://ci-stats.elastic.co/app/apm/services/apm-ci/transactions/view?rangeFrom=2022-02-10T11:13:39.278Z&rangeTo=2022-02-10T11:33:39.278Z&transactionName=apm-agent-java%2Fapm-agent-java-mbp%2Fmain&transactionType=job&latencyAggregationType=avg&comparisonEnabled=true&comparisonType=day&transactionId=6c2dc61e2f5a0654&traceId=21172be540156945c3c6ab6935872b96)
- But the ones for this PR, it's empty -> see [here](https://ci-stats.elastic.co/app/apm/services/apm-ci/transactions/view?rangeFrom=2022-02-10T14:43:50.917Z&rangeTo=2022-02-10T15:03:50.917Z&transactionName=apm-agent-java/apm-agent-java-mbp/PR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=a5c8f2da7cb2aeb151589bdf00256022&transactionId=6e892d7ba7d40459)

I can bump from `1.7` to `1.9` to bisect what's the reason

**Comment by cyrille-leclerc** [comment]
Please bump the otel collector

**Comment by SylvainJuge** [comment]
@v1v do you think we can merge this ? The test failures are not related and seems related to flaky tests.

**Comment by v1v** [comment]
No yet, somehow I don't see the traces in the OTEL backend, so I might need to contact the infra team as somehow the OTEL collector might still point to an old version

**Comment by SylvainJuge** [comment]
The latest version is 1.17.0 (https://github.com/open-telemetry/opentelemetry-java-contrib/releases/tag/v1.17.0), should we update this PR to this latest version or conservatively keep it to 1.10.0 ?

**Comment by v1v** [comment]
We might close it, the existing infrastructure requires further upgrades and syncup with the CI systems team, so a bit tedious atm

**Comment by SylvainJuge** [comment]
I see, I don't mind keeping this one around until we can make progress here, it is up to what you prefer. I have marked it to the `blocked` to reflect that.
Do you have another issue to track all the things that needs to be resolved before we can do the upgrade ?

**Comment by v1v** [comment]
> Do you have another issue to track all the things that needs to be resolved before we can do the upgrade ?

Within this PR there are some issues linked to this one, since those issues are coming from private repositories, I don't want to add anything to avoid any misleading.

**Comment by eyalkoren** [comment]
> Let's keep it open for a bit

@v1v @SylvainJuge what do you say we close this PR as a celebration for its 1-year anniversary? 👶

**Comment by v1v** [comment]
For more context, I closed this as we are moving away from Jenkins, and I could not get any further details about the existing infra in place...

**Pull request closed without merging**
