### PR TITLE
added support to jakartaee in jsf plugin

### PR DESCRIPTION
**Pull request by kananindzya**
## What does this PR do?

relates to #1543 

## Checklist

- [x] This is an enhancement of existing features, or a new feature in existing plugins
  - [x] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)
  - [x] I have added tests that prove my fix is effective or that my feature works
  - [x] I have made corresponding changes to the documentation
  - [x] added integration tests

### CODE REVIEW

**Comment by jackshirazi** [comment]
/test
@elasticmachine run elasticsearch-ci/docs

**Comment by jackshirazi** [comment]
weird test failure. I'll try again
/test

**Comment by v1v** [comment]
@Mergifyio update

**Comment by jackshirazi** [comment]
@elasticmachine run elasticsearch-ci/docs

**Pull request merged**
