### PR TITLE
Support daily snapshots

### PR DESCRIPTION
**Pull request by amannocci**
Signed-off-by: Adrien Mannocci <adrien.mannocci@elastic.co>

## What does this PR do?

* Add a stage to publish snapshots in a GCS bucket.

## Checklist

- [ ] This is an enhancement of existing features, or a new feature in existing plugins
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/main/CHANGELOG.asciidoc)
  - [ ] I have added tests that prove my fix is effective or that my feature works
  - [ ] Added an API method or config option? Document in which version this will be introduced
  - [ ] I have made corresponding changes to the documentation
- [ ] This is a bugfix
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/main/CHANGELOG.asciidoc)
  - [ ] I have added tests that would fail without this fix
- [ ] This is a new plugin
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/main/CHANGELOG.asciidoc)
  - [ ] My code follows the [style guidelines of this project](https://github.com/elastic/apm-agent-java/blob/main/CONTRIBUTING.md#java-language-formatting-guidelines)
  - [ ] I have made corresponding changes to the documentation
  - [ ] I have added tests that prove my fix is effective or that my feature works
  - [ ] New and existing [**unit** tests](https://github.com/elastic/apm-agent-java/blob/main/CONTRIBUTING.md#testing) pass locally with my changes
  - [ ] I have updated [supported-technologies.asciidoc](https://github.com/elastic/apm-agent-java/blob/main/docs/supported-technologies.asciidoc)
  - [ ] Added an API method or config option? Document in which version this will be introduced
  - [ ] Added an instrumentation plugin? Describe how you made sure that old, non-supported versions are not instrumented by accident.
- [ ] This is something else
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/main/CHANGELOG.asciidoc)

Screenshot 2022-12-07 at 12 05 04

### CODE REVIEW

**Review by kuisathaverat — APPROVED** [review]

**Comment by SylvainJuge** [comment]
The snapshots are also published daily to sonatype repository (in internal CI), would it be something that we could also automate from the GCP storage (or bundle them together) to ensure having the same snapshot both in the private GCP and public repositories synchronized ?

While the risk of inconsistency between the two is quite low, having the whole publication in the same pipeline would likely make things simpler.

**Comment by amannocci** [comment]
The mechanism isn't exactly the same. We are publishing each snapshot artifact to a specific GCS bucket to make them available. In the other, Jenkins job we are publishing each snapshot artifact daily. The syntax isn't the same between both Jenkins jobs.
It's possible to adapt the daily job in the other CI to also publish on the GCS bucket.
Do we want each snapshot artifact published on Sonatype nexus on every commit?

**Comment by SylvainJuge** [comment]
> Do we want each snapshot artifact published on Sonatype nexus on every commit?
I don't think that is required, but if we could that would be awesome as it means that once something is merged then the next artifact available publicly would already contain the change. Right now we have to wait until the next day.

We sometimes use snapshots for customer support, but most of the time we can rely on direct links to the CI before the PR is merged. In short that would be a nice bonus but we can definitely live without it.

**Review by SylvainJuge — APPROVED** [review]
LGTM, let's leave sonatype repository as-is for now.

**Pull request merged**
