### PR TITLE
Add Spring WebFlux support

### PR DESCRIPTION
**Pull request by marcin-bukowiecki**
In Spring WebFlux we can create HTTP endpoints in two ways. First one is to annotate our methods in `@RestController` / `@Controller` class with `@GetMapping`, `@PutMapping` etc. This wasn’t difficult but if we want to instrument our HTTP requests our methods must be declared with `org.springframework.web.server.ServerWebExchange` or `org.springframework.http.server.reactive.ServerHttpRequest` argument type (so we can extract some useful data such as: URL etc.).
The second way is to declare our HTTP endpoints in a functional way. This was quite difficult because we can do it in multiple ways. This plugin will work only if we create our functional endpoint by calling `RouterFunctions.route().GET(…)`, `RouterFunctions.route().POST(...)` etc. Plugin will wrap this lambda with a `HandlerFunctionWrapper` class and instrument the `handle(ServerRequest request)` method. To do it simpler I could create a type matcher to match any class and match methods which take `ServerRequest` as a parameter but this was very slow (compiler generates static synthetic methods for lambdas and we search all loaded classes to find this methods).

https://docs.spring.io/spring/docs/current/spring-framework-reference/web-reactive.html

### Checklist

- [x] Implement code
- [x] Add tests
- [x] Update documentation
- [x] Update [CHANGELOG.md](CHANGELOG.md)
- [x] Update [supported-technologies.asciidoc](docs/supported-technologies.asciidoc)
- [ ] Added an API method or config option? Document in which version this will be introduced.

### CODE REVIEW

**Comment by eyalkoren** [comment]
Thanks a lot for the PR!
Sorry about the delay in reviewing, it may take a bit before we get to it, but we will.

**Comment by lreuven** [comment]
ref https://github.com/elastic/apm-agent-java/issues/860

**Comment by felixbarny** [comment]
As this is marked as work in progress, what is currently missing here? Are you using this instrumentation currently in test or even prod?

Note that I'm currently working on Netty instrumentation. That as Netty is used as the foundation of Spring WebFlux, we could have a thinner instrumentation for WebFlux which is only responsible for naming the transactions and possibly for inter-thread context propagation.

**Comment by marcin-bukowiecki** [comment]
Sorry for the delay was on vacation :). I didn’t have any opportunity to test this on production. Also Spring WebFlux can be used with several servers such as Netty, Undertow and Servlet containers. So this implementation is quite universal but only unit tested on Undertow since I had some problems with Netty dependency conflicts.

**Comment by blackleg** [comment]
@marcin-bukowiecki Thanks for your job, but what is the status of this pull request?

**Comment by PGoski** [comment]
Wanted to test integration, built from the source and got an error message at a JVM startup:
`Failed to start agent
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at co.elastic.apm.agent.bci.AgentMain.init(AgentMain.java:85)
	at co.elastic.apm.agent.bci.AgentMain.premain(AgentMain.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.NoClassDefFoundError: org/springframework/web/reactive/function/server/RouterFunctions$Builder
	at co.elastic.apm.agent.spring.webflux.FunctionalHandlerInstrumentation.getTypeMatcher(FunctionalHandlerInstrumentation.java:61)
	at co.elastic.apm.agent.bci.ElasticApmAgent.applyAdvice(ElasticApmAgent.java:177)
	at co.elastic.apm.agent.bci.ElasticApmAgent.initInstrumentation(ElasticApmAgent.java:142)
	at co.elastic.apm.agent.bci.ElasticApmAgent.initInstrumentation(ElasticApmAgent.java:103)
	at co.elastic.apm.agent.bci.ElasticApmAgent.initialize(ElasticApmAgent.java:99)
	... 12 more`

Tested with Java 1.8.0_242 and  spring-boot-starter-webflux:2.2.2.RELEASE

**Comment by dengliming** [comment]
So, Is this pr still in progress?

**Comment by PGoski** [comment]
I've improved #827 and made apm-spring-weblux to work with real life app, added netty support also:
code:
https://github.com/PGoski/apm-agent-java/tree/mb-add-spring-webflux-plugin

jar for testing:
https://github.com/PGoski/apm-agent-java/releases/tag/1.16.1-SNAPSHOT

**Comment by felixbarny** [comment]
superseded by #1221

**Pull request closed without merging**
