### PR TITLE
Use *auth* instead of authorization for sanitizing fields

### LINKED ISSUE #2321: [META 576] Sanitize `*auth*` instead of `authorization`
[issue details](https://github.com/elastic/apm/issues/576)

[issue details](https://github.com/elastic/apm/issues/577)

Sanitize `*auth*` instead of `authorization`

### PR DESCRIPTION
**Pull request by tobiasstadler**
## What does this PR do?
Fixes #2321

## Checklist
- [x] This is something else
  - [x] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)

### CODE REVIEW

**Review by felixbarny — APPROVED** [review]

**Comment by tobiasstadler** [comment]
run elasticsearch-ci/docs

**Comment by felixbarny** [comment]
run elasticsearch-ci/docs

**Comment by tobiasstadler** [comment]
Thank You! Only ~15 left ;-)

**Comment by tobiasstadler** [comment]
No worries. I know you are busy.

**Pull request merged**
