### PR TITLE
Added Support for JBoss Logging to the log correlation plugin

### LINKED ISSUE #1734: Log correlation should support JBoss Logging
## Is your feature request related to a problem?
Wildfly uses JBoss Logging, which is not supported right now.

## Describe the solution you'd like
`MdcActivationListener` should support `org.jboss.logging.MDC`

### PR DESCRIPTION
**Pull request by tobiasstadler**
## What does this PR do?
Fixes #1734

## Checklist
- [x] This is an enhancement of existing features, or a new feature in existing plugins
  - [x] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)
  - [x] I have added tests that prove my fix is effective or that my feature works
  - [x] I have added info about JBoss logging to the [relevant section](https://www.elastic.co/guide/en/apm/agent/java/current/supported-technologies-details.html#supported-logging-frameworks) in the supported technologies page
- [ ] This is a bugfix
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)
  - [ ] I have added tests that would fail without this fix
- [ ] This is a new plugin
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)
  - [ ] My code follows the [style guidelines of this project](https://github.com/elastic/apm-agent-java/blob/master/CONTRIBUTING.md#java-language-formatting-guidelines)
  - [ ] I have made corresponding changes to the documentation
  - [ ] I have added tests that prove my fix is effective or that my feature works
  - [ ] New and existing [**unit** tests](https://github.com/elastic/apm-agent-java/blob/master/CONTRIBUTING.md#testing) pass locally with my changes
  - [ ] I have updated [supported-technologies.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/docs/supported-technologies.asciidoc)
  - [ ] Added an API method or config option? Document in which version this will be introduced
  - [ ] Added an instrumentation plugin? Describe how you made sure that old, non-supported versions are not instrumented by accident.
- [ ] This is something else
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)

### CODE REVIEW

**Review by SylvainJuge — APPROVED** [review]
LGTM, took the opportunity to make test slightly more generic.

**Comment by eyalkoren** [comment]
@tobiasstadler Thanks! ❤️ 

I tested with `3.0.0.GA` and all works as expected (only requires switching to use `getMap().clear()` because the `clear()` API was not yet available) and added an entry to the [supported technologies page](https://www.elastic.co/guide/en/apm/agent/java/current/supported-technologies-details.html#supported-logging-frameworks) accordingly. Please let me know if you want to change something.

Also, I am not familiar enough with this logging library - can it be used in conjugation with slf4j or other? If so, did you verify it behaves as expected in such configuration?

**Comment by tobiasstadler** [comment]
@eyalkoren Thank you for your support.

JBoss Logging itself is just a facade (similar to SLF4J) and needs a backend. The difference to SLFJ is, that some backends (JBoss LogManager, SLF4J, log4j, log4j2, java.until.logging) are packaged together with the api.

I tested it with JBoss LogManager. If the backend is SL4J (or another logging implementation supported by the agent) the MDC is set twice (once using the JBoss Logging api and once using the SLF4J api). but I don‘t think this is a problem as the values are the same. Using SLF4J together with the log4j2 backend should behave in the same way. Do you wan‘t me to test it?

I don‘t think using `getMap().clear()` is a good idea, as e.g. the SLF4J backend calls `org.slf4j. MDC.getCopyOfContextMap()`. AFAIK clearing this map does not affect the original MDC map.

**Comment by eyalkoren** [comment]
> I tested it with JBoss LogManager. If the backend is SL4J (or another logging implementation supported by the agent) the MDC is set twice (once using the JBoss Logging api and once using the SLF4J api). but I don‘t think this is a problem as the values are the same. Using SLF4J together with the log4j2 backend should behave in the same way. Do you wan‘t me to test it?

What happens when it is set twice? If the second overrides the first, then we are OK. 

> I don‘t think using getMap().clear() is a good idea, as e.g. the SLF4J backend calls org.slf4j. MDC.getCopyOfContextMap(). AFAIK clearing this map does not affect the original MDC map.

I don't actually use it in our production code, it was only for testing 3.0.0.GA that couldn't compile with `clear()`. Since tests passed, I was good with that and didn't bother to look into the implementation. Now the tests are reverted to use `clear()` (which is apparently not required, but I don't mind leaving it).

**Comment by tobiasstadler** [comment]
Yes, second one overwrites the first one.

**Pull request merged**
