### PR TITLE
Use epoch micros for intake v2

### PR DESCRIPTION
**Pull request by felixbarny**
see elastic/apm-server#1413

### CODE REVIEW

**Comment by felixbarny** [comment]
After we only support v2, we should improve the JSON schema tests.

**Comment by felixbarny** [comment]
That was initially the plan, which is why I introduced two distinct configuration options but v2 only supports DT. So in practice both flags would be either true or false at the same time.

**Comment by eyalkoren** [comment]
After we move to using V2, wouldn't DT still remain configurable? When the DT flag is `false` we are using V1.

**Comment by felixbarny** [comment]
After we move to using V2, wouldn't DT still remain configurable? No, because the APM Server only supports the DT for mat for intake v2..

**Pull request merged**
