### PR TITLE
Universal bootdelegation

### PR DESCRIPTION
**Pull request by felixbarny**
## Checklist

- [ ] This is an enhancement of existing features, or a new feature in existing plugins
  - [ ] I have updated [CHANGELOG.asciidoc](CHANGELOG.asciidoc)
  - [ ] I have added tests that prove my fix is effective or that my feature works
  - [ ] Added an API method or config option? Document in which version this will be introduced
  - [ ] I have made corresponding changes to the documentation
- [ ] This is a bugfix
  - [ ] I have updated [CHANGELOG.asciidoc](CHANGELOG.asciidoc)
  - [ ] I have added tests that would fail without this fix
- [x] This is a new plugin
  - [x] I have updated [CHANGELOG.asciidoc](CHANGELOG.asciidoc)
  - [x] My code follows the [style guidelines of this project](https://github.com/elastic/apm-agent-java/blob/master/CONTRIBUTING.md#java-language-formatting-guidelines)
  - [x] I have made corresponding changes to the documentation
  - [x] I have added tests that prove my fix is effective or that my feature works
  - [x] New and existing [**unit** tests](https://github.com/elastic/apm-agent-java/blob/master/CONTRIBUTING.md#testing) pass locally with my changes
  - [x] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)
  - [x] I have updated [supported-technologies.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/docs/supported-technologies.asciidoc)
  - [x] Added an API method or config option? Document in which version this will be introduced
  - [ ] ~Added an instrumentation plugin? Describe how you made sure that old, non-supported versions are not instrumented by accident.~
- [ ] This is something else
    - [ ] I have updated [CHANGELOG.asciidoc](CHANGELOG.asciidoc)

### CODE REVIEW

**Comment by felixbarny** [comment]
> The JBoss and WildFly integration tests would fail without the new plugin?

Yes, and also the Payara test which uses an OSGi container.

> Get as much indication as we can that we don't introduce a regression with that.

I was thinking we should do that one we have a release candidate that also contains #1230 so we don't have to ask everyone to test multiple times.

**Comment by eyalkoren** [comment]
@philippkahr Can you test the relevant artifact from [here](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-java%2Fapm-agent-java-mbp/detail/PR-1259/6/pipeline) and see if this works on your Atlassian systems without any special configuration we may have added in the past to deal with OSGi?

**Comment by eyalkoren** [comment]
> I was thinking we should do that one we have a release candidate that also contains #1230 so we don't have to ask everyone to test multiple times.

NP, just asked this once 😊  as this is very OSGi specific. But good idea, once we merge both, let's just keep in mind we want these special tests, specifically Mule which is not a proper OSGi, so would make an interesting case.

**Comment by philippkahr** [comment]
@eyalkoren that works just as expected! Right out of the box, no issue.

What I would suggest is to add e.g. jira with a few different versions to your build / end2end testing pipeline.

`docker run -v /Users/e_pkah/Desktop/setenv.sh:/opt/atlassian/jira/bin/setenv.sh -v /Users/e_pkah/Desktop/elastic-apm-agent-1.17.1-SNAPSHOT.jar:/opt/atlassian/jira/elastic-apm-agent.jar --name="jira" -d -p 8080:8080 atlassian/jira-software`

with that you get a jira container that is ready after a few seconds and you can run a curl against `http://localhost:8080` and check if something is broken ;). I would say, as long as it returns something, that is a good sign.

https://gist.github.com/philippkahr/6c12c99028e5dfc08847edb73dc9f4cf here you go for the successful Catalina log. I added the `setenv.sh` I used, so you can recreate it at any given time.

image

**Comment by SylvainJuge** [comment]
Also, for the record, this change prevents having such awful error messages with Jboss at server shutdown (Jboss EAP 7.3.0) when using runtime attachment.
```
java.lang.NoClassDefFoundError: co/elastic/apm/agent/concurrent/JavaConcurrent
   at org.jboss.threads@2.3.3.Final-redhat-00001//org.jboss.threads.EnhancedQueueExecutor.execute(EnhancedQueueExecutor.java:763)
   at org.jboss.msc@1.4.11.Final-redhat-00001//org.jboss.msc.service.ServiceContainerImpl$ContainerExecutor.execute(ServiceContainerImpl.java:945)
   at org.jboss.msc@1.4.11.Final-redhat-00001//org.jboss.msc.service.ServiceControllerImpl.doExecute(ServiceControllerImpl.java:795)
   at org.jboss.msc@1.4.11.Final-redhat-00001//org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1569)
   at org.jboss.threads@2.3.3.Final-redhat-00001//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
   at org.jboss.threads@2.3.3.Final-redhat-00001//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
   at org.jboss.threads@2.3.3.Final-redhat-00001//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
   at org.jboss.threads@2.3.3.Final-redhat-00001//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
   at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.NoClassDefFoundError: co/elastic/apm/agent/concurrent/JavaConcurrent
   at org.jboss.msc@1.4.11.Final-redhat-00001//org.jboss.msc.service.ServiceContainerImpl$ContainerExecutor.execute(ServiceContainerImpl.java:946)
   at org.jboss.msc@1.4.11.Final-redhat-00001//org.jboss.msc.service.ServiceControllerImpl.doExecute(ServiceControllerImpl.java:795)
   at org.jboss.msc@1.4.11.Final-redhat-00001//org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1569)
   at org.jboss.threads@2.3.3.Final-redhat-00001//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
   at org.jboss.threads@2.3.3.Final-redhat-00001//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
   at org.jboss.threads@2.3.3.Final-redhat-00001//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
   at org.jboss.threads@2.3.3.Final-redhat-00001//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
   at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by felixbarny** [comment]
Runtime attachment was not supported on JBoss before this change

**Pull request merged**
