### PR TITLE
Loading Advice classes lazily when required

### PR DESCRIPTION
**Pull request by eyalkoren**
One step in the direction of complete separation between Advice and Instrumentation classes.
Next step is extract Advice code from all Instrumentations to different classes and it would also make sense to put all advices in separate source files as well.

### CODE REVIEW

**Review by felixbarny — APPROVED** [review]
LGTM

**Comment by felixbarny** [comment]
> and it would also make sense to put all advices in separate source files as well.

Personally, I kind of like instrumentations to be colocated with instrumentations so that it's clearer which method an advice instruments. Do you fear eager linking if it's a static inner class? I don't think it should be an issue as they're compiled into separate class files.

**Comment by eyalkoren** [comment]
> Do you fear eager linking if it's a static inner class? I don't think it should be an issue as they're compiled into separate class files.

No, I agree, there shouldn't be any linkage error due to inner classes. This is just a matter of source code.
It is very misleading to place sources of two classes at the same file, where it is important to load them in different times and with different dependencies. I would even say the ideal encapsulation would be to separate them to two different modules, where the instrumentation class cannot have a dependency in the advice class and the library classes, but I proposed a middle-way that will not require a very tough refactoring. What we have with this PR is only the [javadoc warning](https://github.com/elastic/apm-agent-java/pull/1736/files#diff-4d130dca8badaf3c00f2282a5751067e55ee9c47f9154595f3733e316fb70175R148-R161), but I think it's much easier to miss improper dependencies this way. An example: https://github.com/elastic/apm-agent-java/pull/1657/commits/c86ecb758089722693e620f5cdb7a0c2c11b41ee

**Comment by felixbarny** [comment]
> I think it should fix a problem reported as failing our AsyncServletTest when running on Windows

IINM, it turned out not to be a different linking behavior under Windows but a bug in the package scanning, which has been fixed via https://github.com/elastic/apm-agent-java/pull/1671/commits/c66bdd478847a4f2d276feccf0b95d5dc84a1ea7, right?

Not saying that this change isn't useful, just trying to connect the dots.

**Comment by eyalkoren** [comment]
> IINM, it turned out not to be a different linking behavior under Windows but a bug in the package scanning, which has been fixed via c66bdd4, right?

Right.

**Pull request merged**
