### PR TITLE
fix two problems in dubbo plugin

### PR DESCRIPTION
**Pull request by CoderLan0668**
## What does this PR do?

to fix two problem in dubbo plugin

- ensure that dubbo transaction will only be created at the provider side
- the apm headers will be covered with unexpected value when the application invoke a dubbo api within a dubbo transaction

## Checklist
- [√] This is a bugfix
  - [√] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)
  - [√] I have added tests that would fail without this fix

### CODE REVIEW

**Comment by CoderLan0668** [comment]
@SylvainJuge  Can this PR be merged?

**Comment by CoderLan0668** [comment]
All tests are passed,  So what‘s the problem with this PR?  what can i do to make this pr to be merged early?

**Comment by CoderLan0668** [comment]
> All tests are passed, So what‘s the problem with this PR? what can i do to make this pr to be merged early?

@SylvainJuge @AlexanderWert

**Comment by CoderLan0668** [comment]
> > All tests are passed, So what‘s the problem with this PR? what can i do to make this pr to be merged early?
> 
> @SylvainJuge @AlexanderWert

@felixbarny

**Comment by felixbarny** [comment]
Thanks a lot for your contribution and sorry for the radio silence. We have not forgotten about this PR but we're currently focussing on the tasks that we have planned for in the current [milestone](https://github.com/elastic/apm-agent-java/milestones). I'm sorry that your PR didn't make it on that milestone. I'm adding it as a candidate for the next one.

**Review by SylvainJuge — APPROVED** [review]
I am really sorry it took us that long to get to this PR, as the changes are quite straightforward and properly covered with tests. Thanks a lot @CoderLan0668 ! When pushing to this branch I got a notification that it was renamed as `dubbo_bak` on your fork, are there other changes that we should include here ?

LGTM, I've taken the liberty to switch to using random test ports instead of static ones.

**Comment by SylvainJuge** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by SylvainJuge** [comment]
@elasticmachine run elasticsearch-ci/docs

**Pull request merged**
