### PR TITLE
Add option to make routing-key part of RabbitMQ transaction/span names

### PR DESCRIPTION
**Pull request by deni-topalova**
## What does this PR do?
This PR adds ROUTING_KEY as an option to the `rabbitmq_naming_mode` configuration. It also enables the ability to use that configuration with the `apm-rabbitmq-plugin` in a similar way to how it's done for the [spring-rabbit-plugin](https://github.com/elastic/apm-agent-java/pull/3424). EXCHANGE is the default and does not change the plugin's current behavior. If one chooses ROUTING_KEY, then the names of the rabbit transactions will contain the routing keys instead of the exchange names.
See Issue https://github.com/elastic/apm-agent-java/issues/3415

## Checklist

- [x] This is an enhancement of existing features, or a new feature in existing plugins
  - [x] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/main/CHANGELOG.asciidoc)
  - [x] I have added tests that prove my fix is effective or that my feature works
  - [x] Added an API method or config option? Document in which version this will be introduced
  - [x] I have made corresponding changes to the documentation
- [ ] This is a bugfix
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/main/CHANGELOG.asciidoc)
  - [ ] I have added tests that would fail without this fix
- [ ] This is a new plugin
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/main/CHANGELOG.asciidoc)
  - [ ] My code follows the [style guidelines of this project](https://github.com/elastic/apm-agent-java/blob/main/CONTRIBUTING.md#java-language-formatting-guidelines)
  - [ ] I have made corresponding changes to the documentation
  - [ ] I have added tests that prove my fix is effective or that my feature works
  - [ ] New and existing [**unit** tests](https://github.com/elastic/apm-agent-java/blob/main/CONTRIBUTING.md#testing) pass locally with my changes
  - [ ] I have updated [supported-technologies.asciidoc](https://github.com/elastic/apm-agent-java/blob/main/docs/supported-technologies.asciidoc)
  - [ ] Added an API method or config option? Document in which version this will be introduced
  - [ ] Added an instrumentation plugin? Describe how you made sure that old, non-supported versions are not instrumented by accident.
- [ ] This is something else
  - [x] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/main/CHANGELOG.asciidoc)

### CODE REVIEW

**Review by JonasKunz — COMMENTED** [review]
Thanks for taking the time to implement this!

**Review by JonasKunz — COMMENTED** [review]
LGTM! Could you please sign the CLA, this is required to get the PR merged.
Also because there was a release in between, you'll have to update your PR with the current main-branch and likely need to fix the `CHANGELOG.asciidoc` afterwards.

**Comment by deni-topalova** [comment]
> LGTM! Could you please sign the CLA, this is required to get the PR merged. Also because there was a release in between, you'll have to update your PR with the current main-branch and likely need to fix the `CHANGELOG.asciidoc` afterwards.

Hey @JonasKunz, I updated the PR :) Also, about the CLA, I had signed it the moment I opened the pull request, and now I've just signed it again. Maybe it takes more time to reflect?

**Comment by JonasKunz** [comment]
@deni-topalova you are correct, I can see you in our CLA checker tool.
I think it gets confused because the commit https://github.com/elastic/apm-agent-java/commit/46271065851af9c334c0c1d890b2b32859e3326e was signed with your gtmhub.com email, but the CLA was signed with your quantive.com mail.

I think we can circumvent this issue: Could you squash your commits of this PR to a single commit, ensuring that it only contains you `quantive.com` mail as signature and force push to this PR? 

Sorry for the inconvenience, sometimes the CLA checker is a bit of a pain.

**Comment by JonasKunz** [comment]
Unfortunately your squashed commit (https://github.com/elastic/apm-agent-java/commit/68e0ca2a357c0201cd84508f95b5662c94ba18d2) is still signed with `gtmhub.com` mail:
```
Author: Deniza Topalova <deniza@gtmhub.com>
Date:   Thu May 16 17:53:39 2024 +0300
```

What you alternatively can try to do is sign the CLA again with that mail, if it is easier for you to do. You'll just need to let me know when you've signed, so that I can re-trigger the CLA check.

**Comment by deni-topalova** [comment]
@JonasKunz Yes, I've already done that. Can you please re-trigger the CLA check?

**Comment by JonasKunz** [comment]
run docs-build

**Review by JonasKunz — APPROVED** [review]

**Review by SylvainJuge — APPROVED** [review]

**Pull request merged**
