### PR TITLE
[APM-CI][Java] Add WebLogic container to packer cache

### PR DESCRIPTION
**Pull request by felixbarny**

### CODE REVIEW

**Comment by felixbarny** [comment]
@kuisathaverat do you think that should work? Do we need to `docker login` on the host which builds the CI worker images?

**Comment by kuisathaverat** [comment]
yep, if we use our Docker registry as cache, I am waiting for a namespace for Observability team once we have it, we would put the image in our repository and from there to our packer. I will move this issue to my kanban

**Comment by kuisathaverat** [comment]
@felixbarny it is ready now, we have the image in the private repo. I'd make a PR to test the cache.

**Comment by felixbarny** [comment]
Oh, cool! That was quick :D

**Pull request merged**
