### PR TITLE
Excluding Spring-JMS specific Runnable from the concurrent plugin

### PR DESCRIPTION
**Pull request by eyalkoren**
## What does this PR do?
Yet another stab on fixing the issue reported in [the forum](https://discuss.elastic.co/t/invalid-transactions-grouping-with-activemq/252678), without losing context propagation for JMS-poll-transactions altogether and with minimal effect on anything else.
Supersedes #1483.

## Checklist

- [x] This is a bugfix
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)
  - [x] I have adjusted the current Spring JMS test so that it would fail without this fix

### CODE REVIEW

**Review by felixbarny — APPROVED** [review]
The overall approach LGTM, but tests are failing. Is it related to this PR?

**Comment by eyalkoren** [comment]
> tests are failing. Is it related to this PR?

It must be, but probably related to the concurrency plugin dependency. Checking...

**Comment by eyalkoren** [comment]
Apparently what happened is that since a transaction is created and activated before each test starts, then when registering a `MessageListener`, this is done on a task that runs on a different thread and due to the concurrency plugin, the transaction is activated on this thread. Then, when `onMessge` is invoked, there is an active transaction on that thread, so the receive transaction is not created.

I split the Spring test into a separate module that has the dependencies on Spring JMS and on the concurrency plugin.

**Comment by eyalkoren** [comment]
And now the `pom` thing 🤦 
Fixing...

**Review by felixbarny — APPROVED** [review]

**Pull request merged**
