### PR TITLE
feature - added jetty http client instrumentation

### LINKED ISSUE #1567: jetty http client support.
## Describe the solution you'd like
The jetty client is an HTTP client similar to the okhttp client. It belongs to the subproject of the famous jetty server. Because of its good performance, this client is used in many commercial projects. It would be great if the apm could support this client.

### PR DESCRIPTION
**Pull request by kananindzya**
## What does this PR do?

closes #1567 

## Checklist

- [x] This is a new plugin
  - [X] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)
  - [X] My code follows the [style guidelines of this project](https://github.com/elastic/apm-agent-java/blob/master/CONTRIBUTING.md#java-language-formatting-guidelines)
  - [x] I have made corresponding changes to the documentation
  - [X] I have added tests that prove my fix is effective or that my feature works
  - [X] New and existing [**unit** tests](https://github.com/elastic/apm-agent-java/blob/master/CONTRIBUTING.md#testing) pass locally with my changes
  - [x] I have updated [supported-technologies.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/docs/supported-technologies.asciidoc)

### CODE REVIEW

**Comment by eyalkoren** [comment]
Thanks @kananindzya !! 
As discussed offline, please see if this can be easily converted into an [external plugin](https://github.com/elastic/apm-agent-java/tree/master/integration-tests/external-plugin-test).

**Comment by SylvainJuge** [comment]
Hi @kananindzya 

We discussed this PR with the team, and we think there are two possible paths to make progress on this:
1. keep it as-is and wait for our review, we have low bandwidth right now, thus it might take a while
2. migrate this as an external plugin, which has some drawbacks:
    - not being able to properly set the HTTP request/response fields (for all fields, not specific to HTTP).
    - not being able to reuse existing test infrastructure due to https://github.com/elastic/apm-agent-java/issues/1340 
    
 Thus, either explicitly through dependencies or due to our limited bandwidth, it is currently blocked, I'll tag it appropriately to reflect that. We will keep it open for now until we have a better options to make progress on this. Does it sounds like a good plan for you ?

**Comment by kananindzya** [comment]
> We discussed this PR with the team, and we think there are two possible paths to make progress on this:
> 
> 1. keep it as-is and wait for our review, we have low bandwidth right now, thus it might take a while
> 2. migrate this as an external plugin, which has some drawbacks:
>    
>    * not being able to properly set the HTTP request/response fields (for all fields, not specific to HTTP).
>    * not being able to reuse existing test infrastructure due to [Publish test module for apm-agent-core #1340](https://github.com/elastic/apm-agent-java/issues/1340)
> 
> Thus, either explicitly through dependencies or due to our limited bandwidth, it is currently blocked, I'll tag it appropriately to reflect that. We will keep it open for now until we have a better options to make progress on this. Does it sounds like a good plan for you ?

Hi @SylvainJuge , thanks for review. 
I migrate it here - https://github.com/kananindzya/apm-jetty-httpclient-plugin .

**Comment by SylvainJuge** [comment]
Thanks @kananindzya , I'll close this PR for now as you have migrated to an external plugin.

**Pull request closed without merging**
