### PR TITLE
Moves ServiceInfo to tracer module and reduce dependency exposure to core module of plugins.

### PR DESCRIPTION
**Pull request by raphw**
Introduces a subinterface `ServiceTracer` which indicates support for registering and reading `ServiceInfo` information to enrich trace information.

### CODE REVIEW

**Comment by v1v** [comment]
@mergifyio update

**Comment by raphw** [comment]
`ExternalPluginOTelIT` is failing, what I cannot quite explain by looking at the change set. I also struggle to debug the test, but I am looking into it. If you have any pointers, it's appreciated.

**Comment by JonasKunz** [comment]
run elasticsearch-ci/docs

**Review by JonasKunz — APPROVED** [review]
Looks good, the autodiscovery is now nicely separated.

> ExternalPluginOTelIT is failing, what I cannot quite explain by looking at the change set. I also struggle to debug the test, but I am looking into it. If you have any pointers, it's appreciated.

Did you find out the reason for this? Or did the issue fix itself by rebasing / merging this PR onto the current main?

**Pull request merged**
