### PR TITLE
migrate to indy jaxrs plugin

### PR DESCRIPTION
**Pull request by kananindzya**
refer #1337
hello, `useAnnotationValueForTransactionName` returns `false` during the test. But when `JaxRsTransactionNameInstrumentation` construct `useAnnotationValueForTransactionName`  mocked with `true` value:
```
            if (useAnnotationValueForTransactionName) {
                if (pathAnnotationValue != null) {
                    transactionName = pathAnnotationValue;
                }
            }
```

### CODE REVIEW

**Comment by felixbarny** [comment]
You'll have to use `GlobalVariables` for `useAnnotationValueForTransactionName`, as the `JaxRsTransactionNameInstrumentation` class is loaded twice: once from the system class loader and once from the `IndyPluginClassLoader`. The constructor will only be called for the class loaded by the system class loader. 
The other class will use the initial value of `false`.

**Comment by kananindzya** [comment]
> `GlobalVariables`

Thanks

**Comment by kananindzya** [comment]
@SylvainJuge , @felixbarny  please review this PR
Thanks

**Review by felixbarny — APPROVED** [review]

**Comment by SylvainJuge** [comment]
There is an unexpected `java.lang.IllegalStateException: Cannot resolve type description for co.elastic.apm.agent.httpclient.AbstractHttpClientInstrumentationTest` in the tests, @felixbarny can I let you handle this ?

**Pull request merged**
