### PR TITLE
Tomcat memory leak

### PR DESCRIPTION
**Pull request by eyalkoren**
- [x] Implement code
- [x] Update documentation in code as comment
- [x] Update [CHANGELOG.md](CHANGELOG.md)

### CODE REVIEW

**Comment by eyalkoren** [comment]
Jenkins run the tests

**Comment by mdelapenya** [comment]
Jenkins run the tests please

**Comment by eyalkoren** [comment]
Jenkins run the tests

**Comment by eyalkoren** [comment]
Closing. Seems to be messed up with prior commits, not trigerring CI.
Opened #804 instead.

**Pull request closed without merging**
