### PR TITLE
Load Spring AMQP plugin

### PR DESCRIPTION
**Pull request by hectorespert**
## What does this PR do?

Spring AMQP support is available as a plugin: https://github.com/elastic/apm-agent-java/pull/1657, but it is not loaded by the agent.

## Checklist

- [ ] This is an enhancement of existing features, or a new feature in existing plugins
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)
  - [ ] I have added tests that prove my fix is effective or that my feature works
  - [ ] Added an API method or config option? Document in which version this will be introduced
  - [ ] I have made corresponding changes to the documentation
- [x] This is a bugfix
  - [x] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)
  - [ ] I have added tests that would fail without this fix
- [ ] This is a new plugin
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)
  - [ ] My code follows the [style guidelines of this project](https://github.com/elastic/apm-agent-java/blob/master/CONTRIBUTING.md#java-language-formatting-guidelines)
  - [ ] I have made corresponding changes to the documentation
  - [ ] I have added tests that prove my fix is effective or that my feature works
  - [ ] New and existing [**unit** tests](https://github.com/elastic/apm-agent-java/blob/master/CONTRIBUTING.md#testing) pass locally with my changes
  - [ ] I have updated [supported-technologies.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/docs/supported-technologies.asciidoc)
  - [ ] Added an API method or config option? Document in which version this will be introduced
  - [ ] Added an instrumentation plugin? Describe how you made sure that old, non-supported versions are not instrumented by accident.
- [ ] This is something else
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)

### CODE REVIEW

**Review by eyalkoren — APPROVED** [review]

**Comment by eyalkoren** [comment]
Thanks @hectorespert! 🙏 
Does it work as expected for you with your fix?

**Comment by hectorespert** [comment]
> Thanks @hectorespert! 🙏
> Does it work as expected for  you with your fix?

Yes, I tested it locally and I can see rabbit events.

**Comment by hectorespert** [comment]
Thanks @eyalkoren 
Could be published a patch version with this bugfix?

**Comment by eyalkoren** [comment]
We publish daily [snapshots](https://github.com/elastic/apm-agent-java#snapshots), so today's should contain your fix.
In the mean time, you can download the [latest build artefacts from master](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-java%2Fapm-agent-java-mbp/detail/master/882/artifacts).

**Pull request merged**
