### PR TITLE
Add description about memory pool metrics to docs

### PR DESCRIPTION
**Pull request by eyalkoren**

### CODE REVIEW

**Review by jackshirazi — COMMENTED** [review]
should the `name` comment be the same as the others in the file?
name: The name representing this memory manager (for example G1 Young Generation, G1 Old Generation)

**Comment by eyalkoren** [comment]
> should the name comment be the same as the others in the file?
name: The name representing this memory manager (for example G1 Young Generation, G1 Old Generation)

The other ones are for garbage collectors, not for memory pools.

**Comment by jackshirazi** [comment]
oops, silly me. Do we want to have a similar example? like 
name: The name representing this memory pool (for example Metaspace, Compressed Class Space, G1 Eden Space)

**Comment by eyalkoren** [comment]
> Do we want to have a similar example? like
name: The name representing this memory pool (for example Metaspace, Compressed Class Space, G1 Eden Space)

I don't think this is required - we send those by default, so users can look them up and see what values they get. It may do the opposite and confuse those that use a JVM that uses different names.

**Review by jackshirazi — APPROVED** [review]

**Pull request merged**
