### PR TITLE
add  RocketMQ support

### PR DESCRIPTION
**Pull request by gdutChenxj**
## What does this PR do?
add instrumentation for the Apache RcoektMQ

## Checklist

- [x] My code follows the [style guidelines of this project](CONTRIBUTING.md#java-language-formatting-guidelines)
- [x] I have rebased my changes on top of the latest master branch

- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing [**unit** tests](https://github.com/elastic/apm-agent-java/blob/master/CONTRIBUTING.md#testing) pass locally with my changes

- [x] I have updated [CHANGELOG.asciidoc](CHANGELOG.asciidoc)
- [x] I have updated [supported-technologies.asciidoc](docs/supported-technologies.asciidoc)
- [ ] Added an API method or config option? Document in which version this will be introduced
- [x] Added an instrumentation plugin? How did you make sure that old, non-supported versions are not instrumented by accident?

## Screenshots
<!-- _(Optional)_
Add here screenshots about how the project will be changed after the PR is applied. They could be related to web pages, terminal, etc, or any other image you consider important to be shared with the team.

### CODE REVIEW

**Comment by eyalkoren** [comment]
cla/check

**Comment by eyalkoren** [comment]
@gdutChenxj Thanks! What a great contribution!! 👏 

Some small stuff we need so we can fully review this:
1. We need you to sign the [contributor agreement](https://www.elastic.co/contributor-agreement), otherwise we won't be able to merge this.
2. A description of what the PR does in the PR description itself, generally explaining how it achieves the creation of spans and transactions and distributed tracing.
3. Some comments in the code, at least on the class level saying which instrumentation/helper is related to which client API or scenario (possibly related to the relevant test).

And a couple of questions:
1. Did you test it manually with a real application?
2. I saw that there is a JMS-compliant client as well. Do you know if it is normally used by Java apps, or is the "native" client mostly used?

**Comment by gdutChenxj** [comment]
I signed the agreement a few days ago, but it hasn't been dealt with yet, what else do I need to do about it.

I have added notes to the instrumentation class and tried to explain its scenario,  nothing could be better if you can help me to  improve the comments. I feel very sorry for my poor english.

And i have executed `./mvnw clean test -pl elastic-apm-agent -am -DfailIfNoTests = false -Dtest = ConfigurationExporterTest `and updated configuration.asciidoc - add `meesaging` and `rockemtq` options to disable.

About testing, I set up a springboot project and used RocketMQ in common way to test manually. The following are screenshots of apm data collected by some plugins.
image
image
image


 It should also be noted that because i'm not clear whether the ci environment provides RocketMQ, the unit test is ignored by @Ignore

As for your question (2), I am not quite sure if you are talking about the following project-
[rocketmq-jms](https://github.com/apache/rocketmq-externals/tree/master/rocketmq-jms)
But as far as the developers around me are mostly using the native client.

**Comment by eyalkoren** [comment]
Thanks @gdutChenxj !
I will go over it and suggest initial changes, so we can run tests and then look a bit into more details.

**Comment by eyalkoren** [comment]
OK @gdutChenxj I took a first look. First of all - don't worry about English, yours is very good.
Some pointers:
- Forget about the CHANGELOG change now - remove it and merge your branch with latest master
- It seems you took care of distributed tracing (that is - adding and reading the trace context headers). Does it work for you? I ask because your screenshots don't show it
- I saw you did everything through wrappers. While those are necessary in some cases, we normally try to avoid them as much as possible, because they are risky and they produce "garbage". For example, it is much preferable to find the client method that does the actual message send and instrument it to extract all the info we need and to decorate the message with the trace context headers. If you must rely on something like done in the Kafka plugin for the receiver side, then that's OK, but if you can do without wrapping - that's much better. For the sending part, try to look for a way to avoid wrappers.
- For testing, you will have to setup a RocketMQ broker somehow, either an embedded one (if such exists) or use a test container and a public RocketMQ image (as you can see in the other messaging systems plugins). The end goal is that those tests will run at CI.

**Comment by gdutChenxj** [comment]
About distributed tracing don't work, i think i forget to change the way to start a transaction in the MessageListener Wrapper , i will fix it and add a test for it.

Also, i'm  very grateful to your suggestions and i can't aggree with you any more about  wrapper class. I extract all the info directly as you suggested at first, but when using lambda,  it doesn't work even if the LambdaInstrumentationStrategy.ENABLED option is set and it will throw an AbstractMethodError because the generated anonymous class is missing interface method. I found out that the difference in the methodGraphComplier value of the ByteBuddy instance used caused the error. I will try to find the root cause and fix the problem, but I am not good at using ByteBuddy and it may take some time.

At the same time, I plan to use testcontainer to create RocketMQ for testing. If it works, the test code will be updated soon.

**Comment by gdutChenxj** [comment]
`final ByteBuddy byteBuddy = new ByteBuddy()
            .with(TypeValidation.of(logger.isDebugEnabled()))
            .with(FailSafeDeclaredMethodsCompiler.INSTANCE) // problem setting`

If i use the default Compiler settings, the problems mentioned above will be solved.

**Comment by eyalkoren** [comment]
> About distributed tracing don't work, i think i forget to change the way to start a transaction in the MessageListener Wrapper , i will fix it and add a test for it.

Excellent, thanks! Try to use the Kafka module tests as reference as to what we want to test. It will help you cover all sorts of scenarios and make sure your distributed tracing works as expected.

Regarding the Lambdas - take a look at [the JMS `MessageListener` handling](https://github.com/elastic/apm-agent-java/blob/96b7d60e4edcb39242ab5d7922111d52fd9c1023/apm-agent-plugins/apm-jms-plugin/src/main/java/co/elastic/apm/agent/jms/JmsInstrumentationHelperImpl.java#L134-L143) - it identifies Lambdas and wraps only them when they are registered, thus enabling straightforward instrumentation of the `onMessage` interface method. See if you can do the same. 
Later, we may consider reworking things and enable Lambdas instrumentation, in which case we will be able to just cancel this wrapping.

**Comment by gdutChenxj** [comment]
Following your suggestion,, i  have added some test cases and embedded rocketmq to enable unit tests to run locally, but if there are multiple subclasses of the abstract test class running at the same time, it may cause mq read and write problems, so I used @Ignore to handle some of the sub class

**Comment by gdutChenxj** [comment]
image
The reason it didn't take effect before is that in the MessageListener, the consumption of the message collection is regarded as a transaction, so i start a root transaction. Now it has been modified to start a transaction for each message.

**Comment by eyalkoren** [comment]
cla/check

**Comment by eyalkoren** [comment]
Looks like a nice progress! It may take a bit before we get to fully review, but we will get there.

I ran the build and `RocketMQSyncPullConsumerTest` failed with:
```
[2020-03-12T12:44:03.071Z] Failed tests: 
[2020-03-12T12:44:03.071Z]   RocketMQConcurrentlyPushConsumerTest>AbstractRocketMQConsumerInstrumentationTest.testSendTwoMessage_PartiallyIterate:215->AbstractRocketMQConsumerInstrumentationTest.verifyTracing:449->AbstractRocketMQConsumerInstrumentationTest.verifySendSpanContents:426 
[2020-03-12T12:44:03.071Z] Expecting:
[2020-03-12T12:44:03.071Z]  <"RocketMQ Send Message#Reply-Topic-1">
[2020-03-12T12:44:03.071Z] to be equal to:
[2020-03-12T12:44:03.071Z]  <"RocketMQ Send Message#Request-Topic-1">
[2020-03-12T12:44:03.071Z] but was not.
```

Also, there is still the CLA verification that needs to pass. Did you use the same email you configured in your GitHub account (the one being used to identify you as the commits author)?

**Comment by gdutChenxj** [comment]
Reversing the order of messages may cause the above error, which is related to the state of the rocketmq container. I will try to eliminate this occasional error.

In addition, the email I committhe code is different from the registered email on github. What do I need to do to pass the cla test?

**Comment by eyalkoren** [comment]
I now see that GitHub fails to attribute these commits to you. That wasn't the case before. Did you change something in your GH settings?

In any case, it would be best if you added the same email you use in your gitconfig to your GitHub settings through https://github.com/settings/emails. After you do that, please resign the CLA using this same email.

**Comment by gdutChenxj** [comment]
Is it necessary to set as a private email?

**Comment by eyalkoren** [comment]
> Is it necessary to set as a private email?

That's dependent on your preference.
The CLA check passes now 🎉

**Comment by gdutChenxj** [comment]
I added a wait condition before consume to avoid the problem that consume span committed before send span, and made the container only initialize once to avoid the problem of starting container fail which caused by frequently start and stop. It is successful  to run all tests locally by running `mvn clean test`.

**Comment by eyalkoren** [comment]
@gdutChenxj Thanks for the efforts - tests pass and it's getting closer.
Please review [the pull request](https://github.com/gdutChenxj/apm-agent-java/pull/1) I did on your branch and merge, unless you disagree. In general, the way the Helper was defined cannot work if you use an application that has a local dependency on the RocketMQ client and deploy it on a servlet container due to class loading issues.
In addition, I proposed some other stuff.
Thanks for your great efforts!

**Comment by eyalkoren** [comment]
@gdutChenxj Sorry for the delay, things take longer to get to these days.

The change I did in the tests in your PR were insufficient and there was a bit more required, so I implemented the full fix in a different PR - #1089 .

Please follow this PR and once it is merged to master, merge to your branch (override my changes in `AbstractInstrumentationTest` and `ElasticApmTracer` in your branch with the ones from master).

It may take a bit before I get to do the full review, but I will get to that.

**Comment by gdutChenxj** [comment]
It's ok，and the changes that the tests reuse the same tracer are great!

**Comment by gdutChenxj** [comment]
Hi, is there any problem about your fix pr? It seem take a bit long time

**Comment by eyalkoren** [comment]
> Hi, is there any problem about your fix pr? It seem take a bit long time

No specific problem. We are busy with other things as well. Once it's approved by my peers it will be merged and then you can merge it. This is how we work. Sorry for the delay, but you will have to be patient. Things take a bit longer to complete these days, but we are certainly not neglecting anything.

**Comment by eyalkoren** [comment]
@gdutChenxj #1089 was merged. Please fetch and merge master (override my changes in `AbstractInstrumentationTest` and `ElasticApmTracer` in your branch with the ones from master), then we can proceed. Thanks for your patience.

**Comment by gdutChenxj** [comment]
Ok i'll deal with it right away

**Comment by gdutChenxj** [comment]
code is up to date and unit tests run successfully

**Comment by eyalkoren** [comment]
OK, running the tests on CI. 
Once again, bare with us until we get the chance for a full review, as it won't be immediate, but be assured that we are on it.
Thanks again for your wonderful efforts!

**Comment by eyalkoren** [comment]
Tests failed on CI - please [take a look](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-java%2Fapm-agent-java-mbp/detail/PR-1057/29/tests)

**Comment by gdutChenxj** [comment]
This looks strange. There is no exception when running locally and it  is very similar to the situation that the reporter is different in each sub test class.

**Comment by eyalkoren** [comment]
Either you did not fetch the latest master before merging, or you removed the related changes during your merge. Either way, the #1089 changes are missing in your branch.

**Comment by gdutChenxj** [comment]
I think it's not just the problem. The consumer failed to get the queue in rebalance and caused a timeout. This is an occasional occurrence and needs to be handled.

**Comment by eyalkoren** [comment]
OK, so please handle both and let us know when you feel `mvn clean test` consistently succeeds. We are now in the process of hunting down and eliminating flaky tests, and we certainly don't want to add non-robust tests.
Thanks!

**Comment by gdutChenxj** [comment]
Sorry, the problem seems to be complicated. The cause of the problem may be a bug in rocketmq. and i may need some time to investigate and resolve

**Comment by eyalkoren** [comment]
@gdutChenxj Do you think there is a problem with the instrumentation itself or is it only about the tests? 
I know first hand that writing thorough-yet-stable tests for messaging systems is challenging...
Once you figure it out, please merge with latest master commit and let us know, so we can proceed with it. This PR already contains quite a bit or progress. 
Thanks for investing the time in this plugin!

**Comment by eyalkoren** [comment]
@gdutChenxj Do you have intentions to proceed with this PR?

**Comment by gdutChenxj** [comment]
of course，but i'm busy doing my job，and the reason make test failure is still undefined

**Comment by gdutChenxj** [comment]
The problem is difficult to reproduce locally, and it only appears when using mvn test, there is no way to debug, making the investigation process very difficult

**Comment by eyalkoren** [comment]
@gdutChenxj please see https://github.com/elastic/apm-agent-java/pull/1057#issuecomment-606522730 - it doesn't seem like your branch contains the latest changes (some are related to the tests). 
Start by merging with the current master, commit and push.
Then, we can run the tests on CI and see what happens.

**Comment by eyalkoren** [comment]
Just to clarify - there is no rush on our side. Take as long as you need for that. I was just interested to know if you intend to proceed or abandon the PR.
We highly appreciate your efforts, regardless of the pace you choose 🙂

**Comment by gdutChenxj** [comment]
There is no doubt that it is not you site caused the problem. From the current point of view, the topic used in the test cannot be consumed normally, so the test run failure

**Comment by gdutChenxj** [comment]
I am so sorry that i update my code so late and there is so much work during this time, I refactored the test process to avoid the need for multiple test subclasses to complete the test tasks. At present, it seems that the unit tests are running well, and no exceptions thrown when running `mvn clean test`

**Comment by gdutChenxj** [comment]
I am very sorry to update the code so late. The work of the new department is really very busy. This time I refactored the test process to avoid the need for multiple test subclasses to complete the test task. At present, it seems that the unit test is running well and no exceptions thrown when run `mvn clean test`

**Comment by eyalkoren** [comment]
Don't worry about the pace, there is absolutely no hurry. We highly appreciate your contribution!
It may take a bit on our side to review, but we will get to that.

**Comment by eyalkoren** [comment]
Tests failed 😢 
```
[2020-05-12T10:52:09.196Z] Failed tests: 
[2020-05-12T10:52:09.196Z]   RocketMQInstrumentationTest.testTransactionCreationWithoutContext:418->verifyConsumeTransactionContents:532 
[2020-05-12T10:52:09.196Z] Expecting:
[2020-05-12T10:52:09.196Z]  <752571645f9df64643f38de6d66dae43>
[2020-05-12T10:52:09.196Z] to be equal to:
[2020-05-12T10:52:09.196Z]  <78bf086fd36173e3d11cc9fe7e4845bc>
[2020-05-12T10:52:09.196Z] but was not.
```

**Comment by gdutChenxj** [comment]
Maybe the code of sync consume is not perfect, I will check again

**Comment by eyalkoren** [comment]
@gdutChenxj do you intend to follow up on this at some point?
We currently don't plan to take it actively, but we can assist if you do.

**Pull request closed without merging**
