### PR TITLE
Fix OpenTracing error tag handling

### PR DESCRIPTION
**Pull request by mkavanagh**
## What does this PR do?
Updates the OpenTracing bridge to propagate `span.setTag("error", true)` to the transaction result correctly.

At present, the boolean comparison is inverted so that `span.setTag("error", false)` will propagate to an error result (but `true` will not).

## Checklist

- [x] My code follows the [style guidelines of this project](CONTRIBUTING.md#java-language-formatting-guidelines)
- [x] I have rebased my changes on top of the latest master branch

~~- [ ] I have made corresponding changes to the documentation~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing [**unit** tests](https://github.com/elastic/apm-agent-java/blob/master/CONTRIBUTING.md#testing) pass locally with my changes

- [ ] I have updated [CHANGELOG.asciidoc](CHANGELOG.asciidoc)
~~- [ ] I have updated [supported-technologies.asciidoc](docs/supported-technologies.asciidoc)~~
~~- [ ] Added an API method or config option? Document in which version this will be introduced~~
~~- [ ] Added an instrumentation plugin? How did you make sure that old, non-supported versions are not instrumented by accident?~~

### CODE REVIEW

**Comment by felixbarny** [comment]
Thx for the fix, after signing the CLA, we're good to go 👍

**Comment by mkavanagh** [comment]
Cool - I've signed it, let me know if it's not right somehow

**Comment by felixbarny** [comment]
Looks good. Could you update the changelog?

**Comment by felixbarny** [comment]
Thanks for your contribution!

**Pull request merged**
