### PR TITLE
[APM-CI] Store artifacts in Jenkins

### PR DESCRIPTION
**Pull request by kuisathaverat**
Store the APM Java agent jar file on each Jenkins build

### CODE REVIEW

**Comment by felixbarny** [comment]
Thanks :)

**Comment by eyalkoren** [comment]
@kuisathaverat @felixbarny do you think we should upload `apm-agent-attach-*.jar` as well?

**Comment by felixbarny** [comment]
If you think it's useful, we can definitely do that :)

**Comment by kuisathaverat** [comment]
I take note, I'll make it in a gap between things

**Pull request merged**
