### PR TITLE
Added support for overwriting the service version per classloader

### LINKED ISSUE #1725: Service Version per classloader
## Is your feature request related to a problem?
We deploy multiple wars with different version to a JBoss EAP. Currently we can only set the service version globally for all deployments, but we would like to set the version for each deployment individualy (similar to the service name).

## Describe the solution you'd like
Can we please add `overrideServiceVersionForClassLoader(ClassLoader classLoader, String serviceVersion)` to the Tracer class, so we can use e.g.
```
@WebListener
public class ElasticAPMServiceNameAndVersionContextListener implements ServletContextListener {

    @Override
    public void contextInitialized(ServletContextEvent sce) {
        Tracer tracer = GlobalTracer.get();
        tracer.overrideServiceVersionForClassLoader(getClass().getClassLoader(), "...");
    }
```
to set the service version.

### PR DESCRIPTION
**Pull request by tobiasstadler**
## What does this PR do?
Fixes #1725

## Checklist
- [x] This is an enhancement of existing features, or a new feature in existing plugins
  - [x] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)
  - [x] I have added tests that prove my fix is effective or that my feature works
  - [ ] Added an API method or config option? Document in which version this will be introduced
  - [ ] I have made corresponding changes to the documentation
- [ ] This is a bugfix
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)
  - [ ] I have added tests that would fail without this fix
- [ ] This is a new plugin
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)
  - [ ] My code follows the [style guidelines of this project](https://github.com/elastic/apm-agent-java/blob/master/CONTRIBUTING.md#java-language-formatting-guidelines)
  - [ ] I have made corresponding changes to the documentation
  - [ ] I have added tests that prove my fix is effective or that my feature works
  - [ ] New and existing [**unit** tests](https://github.com/elastic/apm-agent-java/blob/master/CONTRIBUTING.md#testing) pass locally with my changes
  - [ ] I have updated [supported-technologies.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/docs/supported-technologies.asciidoc)
  - [ ] Added an API method or config option? Document in which version this will be introduced
  - [ ] Added an instrumentation plugin? Describe how you made sure that old, non-supported versions are not instrumented by accident.
- [ ] This is something else
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)

### CODE REVIEW

**Comment by tobiasstadler** [comment]
@felixbarny Is there any chance to get this merged?

**Comment by felixbarny** [comment]
I'm out for a bit, will leave this to the team to decide.

**Comment by tobiasstadler** [comment]
Ok, Thank you for the info.

@SylvainJuge @eyalkoren What is your opinion?

**Comment by SylvainJuge** [comment]
FYI, I will also be off for a couple of weeks.

From what I recall we previously agreed that fixing that more generally would be a better option (https://github.com/elastic/apm-agent-java/issues/1327), while it's not without challenges, especially when relying on packaging conventions, I think it would probably a better option to solve the general case.

**Comment by tobiasstadler** [comment]
@SylvainJuge It would be great if #1327 is supported, but as far as I know nobody is working on this. I also think that #1327 can build in this PR.

**Comment by tobiasstadler** [comment]
@SylvainJuge If this will be merged I could use it in https://github.com/tobiasstadler/apm-wildfly-deployment-plugin to set the service version (in addition to the service name)

**Comment by tobiasstadler** [comment]
@SylvainJuge / @felixbarny Any News?

**Comment by SylvainJuge** [comment]
Hi @tobiasstadler, we have added this to our short-term backlog.
While we can't provide guarantees nor ETA, we will try to handle it soon.

**Comment by tobiasstadler** [comment]
Thank You! I am looking forward to it.

**Comment by tobiasstadler** [comment]
I had hoped to get this into 1.27, but I guess I have to wait then

**Comment by tobiasstadler** [comment]
Any chance this will make it into 1.28.0?

**Comment by tobiasstadler** [comment]
Any chance this will make it into 1.29.0?

**Comment by felixbarny** [comment]
After merging and consolidating with #1922, I don't have objections to this PR.

**Comment by tobiasstadler** [comment]
I will use `ServiceInfo` instead of `ServiceNameAndVersion` once #1922 is merged.

**Review by felixbarny — APPROVED** [review]

**Comment by felixbarny** [comment]
run elasticsearch-ci/docs

**Comment by felixbarny** [comment]
Thanks for the contribution and for gently pushing for it ❤️

**Review by felixbarny — APPROVED** [review]

**Comment by felixbarny** [comment]
run elasticsearch-ci/docs

**Comment by tobiasstadler** [comment]
Thank you very much!

**Pull request merged**
