### PR TITLE
Added support for setting destination.address/port on JMS (client) spans who use ActiveMQ Artemis as underlying technology

### LINKED ISSUE #1904: Support for destination.address/port in ActiveMQ Artemis Client
## Is your feature request related to a problem?
We are sending JMS messages to a ActiveMQ Artemis broker.

## Describe the solution you'd like
It would be nice if destination.address/port of the JMS (client) span are pupated with the broker ip/port.

## Describe alternatives you've considered
none

### PR DESCRIPTION
**Pull request by tobiasstadler**
## What does this PR do?
Fixes #1904

## Checklist
- [x] This is a new plugin
  - [x] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc)
  - [x] My code follows the [style guidelines of this project](https://github.com/elastic/apm-agent-java/blob/master/CONTRIBUTING.md#java-language-formatting-guidelines)
  - [x] I have made corresponding changes to the documentation
  - x] I have added tests that prove my fix is effective or that my feature works
  - [x] New and existing [**unit** tests](https://github.com/elastic/apm-agent-java/blob/master/CONTRIBUTING.md#testing) pass locally with my changes
  - [ ] I have updated [supported-technologies.asciidoc](https://github.com/elastic/apm-agent-java/blob/master/docs/supported-technologies.asciidoc)
  - [ ] Added an API method or config option? Document in which version this will be introduced
  - [ ] Added an instrumentation plugin? Describe how you made sure that old, non-supported versions are not instrumented by accident.

### CODE REVIEW

**Comment by tobiasstadler** [comment]
I don't think this litte enhancement is worth an entry in supported-technologies.asciidoc

**Comment by eyalkoren** [comment]
Thanks a lot for your awesome contributions @tobiasstadler !!
FYI, we very recently extended our public API to enable setting `destination.address` and `destination.port` (#1788), which would make this PR another great candidate for an external plugin. Would you like to convert this one as well?
This addition was not yet released, but in the mean time you can test it by using the [latest snapshot](https://github.com/elastic/apm-agent-java#snapshots).

**Comment by eyalkoren** [comment]
(didn't mean to close - wrong button 🤦 )

**Comment by tobiasstadler** [comment]
@eyalkoren Personally, I prefer having this in tree. But I am also fine with me maintaining this as an external plugin, if you prefer that.

**Comment by tobiasstadler** [comment]
BTW. Do you already know when 1.25.0 will be released?

**Comment by eyalkoren** [comment]
> Personally, I prefer having this in tree. 

Why? What's the benefit for you? I'm interested because we want to make our external-plugin contribution experience at least as easy to use/maintain, so any feedback that can help us improve would be great

> I am also fine with me maintaining this as an external plugin, if you prefer that

We do prefer that in this case. Note that these external plugins can still be publicly available to anyone interested and we highly encourage that. 
Keep your external plugins on a dedicated clean GitHub repo and we'll make sure to find a proper way to publish them. In the mean time, you can link them from https://github.com/elastic/apm-contrib/tree/master/apm-agent-java/frameworks, so that we can take it from there once we decide on a proper location in our main repo and/or docs.

> BTW. Do you already know when 1.25.0 will be released?

Not yet, not this week, but hopefully in the next week or two.

Thanks again for your awesome contributions and feedback!

**Comment by tobiasstadler** [comment]
The are two reasons why I prefer having it in tree:
* If it is in your repo you will do the maintenance (if necessary) ;-)
* Without `co.elastic.apm.agent.AbstractInstrumentationTest` (wich is in elastic-apm-core and not published to Maven Central) testing the plugin is way more effort

**Comment by tobiasstadler** [comment]
Ok, I will create an external plugin.

**Comment by eyalkoren** [comment]
> Without co.elastic.apm.agent.AbstractInstrumentationTest (wich is in elastic-apm-core and not published to Maven Central) testing the plugin is way more effort

In case you are not familiar with it already, check out our [external plugin example](https://github.com/elastic/apm-agent-java/tree/master/integration-tests/external-plugin-test/external-plugin ), it does show how to use our tests utilities. In this plugin module there is an example for a unit test, and if you go one level up you can see how we do an integration test for this demo plugin.
I hope this can assist.

Worth noticing: the external plugin mechanism is still experimental, so things may change. However, the intention is that any external plugin you develop now will continue working with future releases, even if we change the API or move to a different approach.

**Comment by tobiasstadler** [comment]
The external plugin uses apm-agent-core as a test dependency. As apm-agent-core is not on maven central (at least I didn't find it there) I have to build it manually first (with the right version) before I can build the plugin. This makes it kinda hard to use CI.

**Comment by eyalkoren** [comment]
It can still be developed within your fork of the Java agent.
What would be the ideal infrastructure that facilitates external plugin development in your view?

**Comment by tobiasstadler** [comment]
FYI: You can find the external plugin here: https://github.com/tobiasstadler/apm-activemq-artemis-destination-plugin

**Comment by felixbarny** [comment]
> apm-agent-core is not on maven central

Good catch, I wasn't aware of that. Sounds like we should publish it by removing this line:

https://github.com/elastic/apm-agent-java/blob/ba97d16ecbd817bc09f01c04cdf46c09dc4685f6/apm-agent-core/pom.xml#L21

**Comment by tobiasstadler** [comment]
Although publishing apm-agent-core would solve my problem, I don't know if it is a good idea to do so (from your perspective ). Publishing apm-agent-core also means "exposing" the internal implementation to plugin developers. 

At the moment I am using an apm-server that is mocked by mock-server (similar to your integration-tests) to capture and validate the created transactions, spans and errors.

**Pull request closed without merging**
