### PR TITLE
Update setup-javaagent.asciidoc

### PR DESCRIPTION
**Pull request by golino**
Update the cloud foundry deploy with more details about the configuration.
Replace `server_url` to `server_urls`;
Explain where are `server_url` and `secret_token`.

## Checklist

- [ ] This is an enhancement of existing features, or a new feature in existing plugins
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/main/CHANGELOG.asciidoc)
  - [ ] I have added tests that prove my fix is effective or that my feature works
  - [ ] Added an API method or config option? Document in which version this will be introduced
  - [x] I have made corresponding changes to the documentation
- [ ] This is a bugfix
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/main/CHANGELOG.asciidoc)
  - [ ] I have added tests that would fail without this fix
- [ ] This is a new plugin
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/main/CHANGELOG.asciidoc)
  - [ ] My code follows the [style guidelines of this project](https://github.com/elastic/apm-agent-java/blob/main/CONTRIBUTING.md#java-language-formatting-guidelines)
  - [ ] I have made corresponding changes to the documentation
  - [ ] I have added tests that prove my fix is effective or that my feature works
  - [ ] New and existing [**unit** tests](https://github.com/elastic/apm-agent-java/blob/main/CONTRIBUTING.md#testing) pass locally with my changes
  - [ ] I have updated [supported-technologies.asciidoc](https://github.com/elastic/apm-agent-java/blob/main/docs/supported-technologies.asciidoc)
  - [ ] Added an API method or config option? Document in which version this will be introduced
  - [ ] Added an instrumentation plugin? Describe how you made sure that old, non-supported versions are not instrumented by accident.
- [ ] This is something else
  - [ ] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/main/CHANGELOG.asciidoc)

### CODE REVIEW

**Comment by golino** [comment]
run elasticsearch-ci/docs

**Comment by eyalkoren** [comment]
@golino Thanks for proposing these clarifications.
@bvader Please review this one.
One thing I can contribute is that we do want to keep `server_url` in the docs as the cross-agents aligned config option, even though we still support `server_urls` - see #1507 for details

**Comment by golino** [comment]
Hi @SylvainJuge !
The target version of this PR is because the [edit](https://github.com/elastic/apm-agent-java/edit/1.x/docs/setup-javaagent.asciidoc) link of the [doc](https://www.elastic.co/guide/en/apm/agent/java/current/setup-javaagent.html#setup-cloud-foundry) is targeting the specific version `1.x`.

**Comment by SylvainJuge** [comment]
@elasticmachine run elasticsearch-ci/docs

**Review by bvader — COMMENTED** [review]
@eyalkoren @golino  

Lines 229 - 232 are not required nor correct and should be deleted. 

> The APM Server in your Elasticsearch service must be enabled:
> 
> `cf update-service my-elastic-service -c '{ "EnableAPMServer": true }'`


The settings described in this section are in a Cloud Foundry User Provided service (cups) specific to the Elastic APM Agent and are simply client side settings that are passed to the the client app deployed in Cloud Foundry and are read by the Elastic Java APM agent. 

These settings have nothing to do with running other Elastic components within Cloud Foundry. 

Line 241 is not technically correct either the bind is between the client application and the cups... not directly to the Elasticsearch service... the end result is the Client Apps' Elastic Java Agent will be properly configured to send data to the Elastic APM Agent... but in Cloud Foundry terminology it is bound to the local service not directly to the Elasticsearch Service.

**Comment by golino** [comment]
@bvader
Some lines were added to facilitate the understand of solution and the deployment.
They can be removed if nor desired on Elastic docs.

The change `server_url` -> `server_urls` was created because the `server_url` was not working with cups.
Also, I changed from cups to run the agent inside the docker image, with the application, but the environment variable `ELASTIC_APM_SERVER_URLS` (with **S**) is required.

Line 241 make no sense using cups. Will remove the change.

- [ ] Remove lines 229 - 232
- [ ] Remove change line 241
- [ ] Review usage of `URLS` or `URL`

**Review by bvader — APPROVED** [review]
LGTM Now

**Review by bvader — APPROVED** [review]

**Review by SylvainJuge — APPROVED** [review]

**Comment by SylvainJuge** [comment]
@elasticmachine run elasticsearch-ci/docs

**Pull request merged**
